### ISSUE TITLE
Server 2019: License is expired

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#10]
hi,

i just tried your latest Server 2019 images (20190101.01) and it seems the license is expired :(

https://app.vagrantup.com/peru/boxes/windows-server-2019-datacenter-x64-eval/versions/20190101.01

The VM is unexpectedly shutdown because WLM.EXE tells License is expired :)
Probably something went wrong during sysprep phase.

**Comment by abbbi** [comment]
Probably you are hitting this:

https://social.technet.microsoft.com/Forums/en-US/a7638653-0588-456d-aa6d-d432da51d7ad/grace-period-windows-server-2019-eval?forum=winserversetup

**Comment by ruzickap** [comment]
You are right - I can see it too: "License is expired".

I'll rebuild the images to see if it is just one time issue or if it is something what needs to be troubleshooted...

Thanks for reporting it - I'll come back to you when the new images will be uploaded to `vagrantup.com`.

**Comment by abbbi** [comment]
I rebuilt the standard eval version with your scripts and it works flawless, seems the most recent iso image provided by microsoft solves this issue.

Thanks for your work! Awesome Image i can use with terraform / libvirt

**Comment by ruzickap** [comment]
Hello.

I rebuilt all images, can you please use the latest images and try it again?

Let me know if it's still "broken"...

Thank you....
