### ISSUE TITLE
wrong usename

### ISSUE THREAD

**Issue by vtraida** [ruzickap/packer-templates#12]
facing with issue with https://app.vagrantup.com/peru/boxes/windows-10-enterprise-x64-eval
after 
vagrant up 
....
default: WinRM transport: ssl
    default: Warning: Authentication failure.

You are using 
config.winrm.username = "Administrator"

but is Windows this user is disabled, after changing to config.winrm.username = "vagrant"
i managed to boot without errors
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'peru/windows-10-enterprise-x64-eval' version '20190220.01' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 3389 (host) (adapter 1)
    default: 5986 (guest) => 5986 (host) (adapter 1)
    default: 5985 (guest) => 55985 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 127.0.0.1:5986
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: ssl
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.2.18
    default: VirtualBox Version: 6.0

**Comment by vtraida** [comment]
First of all i'm very thankful for all your efforts! 
 Here  https://app.vagrantup.com/peru/boxes/windows-10-enterprise-x64-eval
is mentioned 
Login Credentials
Username: Administrator, vagrant
Password: vagrant

**Comment by ruzickap** [comment]
Hello.

I rebuilt all images, can you please use the latest images and try it again?

Let me know if it's still "broken"...

Thank you....

**Comment by vtraida** [comment]
now it's fine, thank you!
one more question about running this image on windows os, i understand i need change default forwarded ports:
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct:true
  # Port forward for WinRM
  config.vm.network :forwarded_port, guest: 5986, host: 5986, id: "winrm-ssl", auto_correct:true


could you please advice and add it to official description?

**Comment by ruzickap** [comment]
Actually these lines with `forwarded_port` are already part of the Vagrantfile inside all "Windows boxes":

https://github.com/ruzickap/packer-templates/blob/791949ee7e257bd6b10d374daa017b277802d3a0/Vagrantfile-windows.template#L25-L28

It should be working...

**Comment by vtraida** [comment]
i manage to work with adding this to my Vagrantfile on win10 host
`config.winrm.port  = 4545
  config.winrm.guest_port = 4545
  config.vm.network :forwarded_port, guest: 5986 , host: 4545, id: "winrm_windows", auto_correct:true`

**Comment by vtraida** [comment]
user name fixed,thank you!
