### ISSUE TITLE
Keep historical releases in vagrant cloud

### ISSUE THREAD

**Issue by tu-nv** [ruzickap/packer-templates#13]
First, thank you for your great work.
This is not really a bug, just for user convenience.

Your release in vagrant cloud only has latest release, e.g.: https://app.vagrantup.com/peru/boxes/ubuntu-16.04-server-amd64
So if Vagrant file uses a specific box version, it will become invalid after new release.

Could you somehow keep the historical box images in varant cloud?

**Comment by ruzickap** [comment]
Hello.

You are right - there is no history of all the images.

The reason why I'm always deleting the "old versions" is that all images I'm building https://app.vagrantup.com/peru has about 35G in total. 
I'm building new images every month to have them updated.
If I keep the history of all the images it will consume (12*35g = 420Gb) per year - which is a lot of data and I do not want to waste such space on vagrantup.com.

The vagrant images aim to be used for testing (not for long term run) - that's the reason why I'm building them every month.

I hope this answer your question...

**Comment by jbeshay** [comment]
@ruzickap, I have the same question concerning the Windows image. I use your libvirt box for automated testing on several machines. The VM is re-provisioned every few hours. Without having historical releases available, all of my machines have to re-download the box image every month. I certainly understand the motivation of reducing the storage load on vagrantup.com but I think instead this is adding bandwidth load. 

How about maintaining a short-term and a long-term release? In case of Windows, the long-term release can last for 160 days (the evaluation period is 180 days). Using this release will avoid re-downloading the box every month on all machines and reduce the bandwidth strain on vagrant up.

**Comment by ruzickap** [comment]
I believe you do not need to use the latest image. 

If you have already download the image to your workstation/server you can use it without downloading the latest one. 

Vagrant will just notice you, that there is new version of the box/image available, but it doesn't force you to download it...

**Comment by jbeshay** [comment]
I see. That makes sense based upon the information https://www.vagrantup.com/docs/boxes/versioning.html

Thank you.
