### ISSUE TITLE
Ansible wsman error

### ISSUE THREAD

**Issue by steve4444** [ruzickap/packer-templates#14]
After a recent system update in Arch Linux, when running 

    ./build.sh windows-10-enterprise-x64-eval-libvirt      

I get an ansible communication error: 

    2019/05/02 19:19:20 packer: 2019/05/02 19:19:20 [INFO] (shell-local communicator): Executing local shell command [/bin/sh -c ANSIBLE_CONFIG='ansible/ansible.cfg' PACKER_BUILDER_TYPE='qemu' PACKER_BUILD_NAME='qemu' PACKER_HTTP_IP='10.0.2.2'  /***/box/packer_cache/packer-shell214238988]
        qemu: PLAY [all] *********************************************************************
        qemu: TASK [Gathering Facts] *********************************************************
        qemu: fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "ssl: HTTPSConnectionPool(host='127.0.0.1', port=2299): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2021ed3048>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
        qemu: PLAY RECAP *********************************************************************
        qemu: 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0
        qemu: ===============================================================================
        qemu: Gathering Facts --------------------------------------------------------- 0.08s
    2019/05/02 19:19:21 [INFO] (telemetry) ending shell-local
    2019/05/02 19:19:21 packer: 2019/05/02 19:19:21 failed to unlock port lockfile: close tcp 127.0.0.1:5918: use of closed network connection
    2019/05/02 19:19:21 packer: 2019/05/02 19:19:21 failed to unlock port lockfile: close tcp 127.0.0.1:5990: use of closed network connection

Note that, after the system update, building did not start without removing  the  "_comment" entry in `windows.json`.

**Comment by ruzickap** [comment]
Hello.

May I ask you to use the following command please:

```bash
export PACKER_LOG=1
./build.sh windows-10-enterprise-x64-eval-libvirt    
```

Paste me the output somewhere where I can look at it.

Thank you

**Comment by netoarmando** [comment]
I had the same problem but running Fedora 29.
Here is a complete log: https://pastebin.com/TtvbupCq

However, I called `packer` directly after exporting all the variables.

**Comment by ruzickap** [comment]
Thanks for reporting it. 
It looks like new packer 1.4.0 brings this problem... 
I'll try to fix it asap...

**Comment by ruzickap** [comment]
Ok it looks like there is a bug in Packer 1.4.0, which ignores the `ssh_host_port_min` and `ssh_host_port_max` parameters.

I can see in your log these lines:

```text
2019/05/05 15:38:16 packerio: 2019/05/05 15:38:16 Looking for available communicator (SSH, WinRM, etc) port between 2299 and 2299
2019/05/05 15:38:16 packerio: 2019/05/05 15:38:16 Trying port: 5996
==> qemu: Found port for communicator (SSH, WinRM, etc): 5996.
```

It means instead of using port `2299` packer choose port `5996` and Ansible is not able to connect to the Windows machine on dedicated port `2299`.

I opened the issue for this: https://github.com/hashicorp/packer/issues/7607

For now the only way is to use Packer 1.3.* for building the images.

**Comment by ruzickap** [comment]
If you need Packer 1.4.0 please use the version mentioned in this ticket https://github.com/hashicorp/packer/issues/7607 (https://github.com/hashicorp/packer/files/3149997/packer.zip), where the issue is fixed.

Otherwise you need to wait for official Packer 1.4.1.

**Comment by steve4444** [comment]
thank you @ruzickap
