### ISSUE TITLE
Feature `synic` requires `vpindex` which isn't defined in Vagrantfile-windows.template

### ISSUE THREAD

**Issue by dragon788** [ruzickap/packer-templates#149]
```
 INFO interface: error: There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: Hyper-V SynIC (requested by 'hv-synic' cpu flag) requires Hyper-V VP_INDEX ('hv-vpindex')
2020-07-23T14:42:04.725568Z qemu-system-x86_64: kvm_init_vcpu failed: Function not implemented
There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: Hyper-V SynIC (requested by 'hv-synic' cpu flag) requires Hyper-V VP_INDEX ('hv-vpindex')
2020-07-23T14:42:04.725568Z qemu-system-x86_64: kvm_init_vcpu failed: Function not implemented
```

**Comment by ruzickap** [comment]
Thank for submitting this. 
May I ask you which versions of libvirt + qemu are you using?

**Comment by dragon788** [comment]
I'm using the ones available from Debian Buster (on a Chromebook under Crostini but it's the same packages).

**Comment by ruzickap** [comment]
I'm running QEMU 4.2.0 on Ubuntu 20.04.

```
$ qemu-system-x86_64 --version
QEMU emulator version 4.2.0 (Debian 1:4.2-3ubuntu6.1)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

$ uname -a
Linux mymachine 5.4.0-26-generic
```

Are you using the QEMU 3.x.x in your environment (https://packages.debian.org/buster/qemu)?

I'm trying to understand which versions of QEMU requires the `synic` + `vpindex` parameter, because I have never seen such "requirement" before.

**Comment by dragon788** [comment]
Here's what I have available:

```
dragon788@penguin:~/win10-vagrant$ kvm --version
QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u7)
Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers
dragon788@penguin:~/win10-vagrant$ qemu-system-x86_64 --version
QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8+deb10u7)
Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers
dragon788@penguin:~/win10-vagrant$ virt-manager --version
2.0.0
dragon788@penguin:~/win10-vagrant$ virsh --version
5.0.0
```

**Comment by dragon788** [comment]
It wasn't until I stumbled across your Vagrantfile-windows.template in plain text that I noticed that it didn't have the `vpindex` set, and it had escaped me that I was on an older qemu from before it became implicit and automatically set by qemu when going to run.

https://bugzilla.redhat.com/show_bug.cgi?id=1738244#c8

And then I had the same issue this poster did of missing the fact that while the number of elements in the two XML arrays were close, a couple of the lines were totally different.

https://unix.stackexchange.com/a/534191/103652
