### ISSUE TITLE
error after vm rename

### ISSUE THREAD

**Issue by vtraida** [ruzickap/packer-templates#15]
[Vagrantfile.txt](https://github.com/ruzickap/packer-templates/files/3157149/Vagrantfile.txt)

I'm using windows 10 as host machine, after vagrant up machine reboots one time after renaming and everything is fine. When I reload or halt machine i get error during connection after rename and reboot
[issue.txt](https://github.com/ruzickap/packer-templates/files/3157170/issue.txt)

Workaround for this case is to change file:
C:\Users\pear\.vagrant.d\boxes\peru-VAGRANTSLASH-windows-10-enterprise-x64-eval\20190405.01\virtualbox\Vagrantfile
   **config.winrm.username = "Administrator"
  #config.winrm.username = "vagrant"**
and then no errors

c:\vm\w10clean>vagrant halt
==> w10VM: Attempting graceful shutdown of VM...

c:\vm\w10clean>vagrant up
Bringing machine 'w10VM' up with 'virtualbox' provider...
==> w10VM: Checking if box 'peru/windows-10-enterprise-x64-eval' version '20190405.01' is up to date...
==> w10VM: Clearing any previously set forwarded ports...
==> w10VM: Clearing any previously set network interfaces...
==> w10VM: Preparing network interfaces based on configuration...
    w10VM: Adapter 1: nat
    w10VM: Adapter 2: bridged
==> w10VM: Forwarding ports...
    w10VM: 3389 (guest) => 3389 (host) (adapter 1)
    w10VM: 5986 (guest) => 5986 (host) (adapter 1)
    w10VM: 4444 (guest) => 4444 (host) (adapter 1)
    w10VM: 5986 (guest) => 4545 (host) (adapter 1)
    w10VM: 5985 (guest) => 55985 (host) (adapter 1)
    w10VM: 22 (guest) => 2222 (host) (adapter 1)
==> w10VM: Running 'pre-boot' VM customizations...
==> w10VM: Booting VM...
==> w10VM: Waiting for machine to boot. This may take a few minutes...
    w10VM: WinRM address: 127.0.0.1:4545
    w10VM: WinRM username: Administrator
    w10VM: WinRM execution_time_limit: PT2H
    w10VM: WinRM transport: ssl
==> w10VM: Machine booted and ready!
==> w10VM: Checking for guest additions in VM...
==> w10VM: Setting hostname...
==> w10VM: Waiting for machine to reboot...
==> w10VM: Configuring and enabling network interfaces...
==> w10VM: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> w10VM: flag to force provisioning. Provisioners marked to run always will still run.`

**Comment by ruzickap** [comment]
May I ask you to send me all commands which I can use to simulate the issue please?

Thanks...
