### ISSUE TITLE
eval license runs out from the date the image is released

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#158]
hi,

it seems this issue is back since some time, i noticed a few months ago but just came around it again. If a freshly added libvirt box is spinned up, the license eval has already started to run out, showing the days since you have released the image to be gone .. It works out as you are releasing a new version within that timeframe, but once you stop, the boxes will become unusable after 180 days :)

I just tried with the last released  2019 box ('peru/windows-server-2019-standard-x64-eval' (v20200801.01) for libvirt
For those boxes the evaluation license already down to 177 days, if freshly spinned up.

I havent checked with the latest release you did today, (v20200803.01) but seems likey those will show the same situation after a few days have passed by.

I guess somethings going wrong during sysprep ..
_Originally posted by @abbbi in https://github.com/ruzickap/packer-templates/issues/3#issuecomment-668219346_

**Comment by ruzickap** [comment]
Hello.

You are probably right. 
These images should be used for testing proposes or some "short-term actions". I do not expect anybody to use the same image for more than 2 or 3 months.

That's why I'm releasing the new images every month. Every new image should be fully up to date with latest software / security patches / updates / ... 
Using anything "older" doesn't make sense. (Older images are removed from Vagrant Cloud anyway).

I'm not sure how it is with sysprep + licenses but the reasons why you should not bother about it are written above.

If I stop releasing the news boxes than users needs to do their own builds, because Windows images will stop working due to the licencing problems you described.

Anyway - if you have any kind of "legal licensing improvement", which I can implement, I'm happy to do it if you create the PR.

Thank you

**Comment by abbbi** [comment]
hi,

i just find it strange that the countdown of the evaluation period starts even as you sysprep the image.. as far as i know, that shouldnt be the case, because running sysprep via  with options "/generalize /shutdown", should rearm the image, after that
the evaluation countdown should be reset to 180 days. At least, thats what i find on technet for that topic.

One other way to re-start the evaluation period (possible up to 6 times) is the following command:

slmgr.vbs -rearm

after a reboot, the evaluation period is back to 180 days.

**Comment by abbbi** [comment]
hi,

i think the SkipRearm statement causes the situation:

 https://github.com/ruzickap/packer-templates/blob/master/scripts/win-common/unattend.xml#L5

**Comment by ruzickap** [comment]
Thanks for pointing it out. 

I'll try to remove the `<SkipRearm>1</SkipRearm>` form https://github.com/ruzickap/packer-templates/blob/4aefc7a80788f9e6776fcaf8e07351c292c1db36/scripts/win-common/unattend.xml#L5 and run some tests to see how it will behave...

**Comment by abbbi** [comment]
> Thanks for pointing it out.
> 
> I'll try to remove the `<SkipRearm>1</SkipRearm>` form
> 
> https://github.com/ruzickap/packer-templates/blob/4aefc7a80788f9e6776fcaf8e07351c292c1db36/scripts/win-common/unattend.xml#L5
> 
> and run some tests to see how it will behave...

Thanks for pointing it out.

I'll try to remove the `<SkipRearm>1</SkipRearm>` form

https://github.com/ruzickap/packer-templates/blob/4aefc7a80788f9e6776fcaf8e07351c292c1db36/scripts/win-common/unattend.xml#L5

and run some tests to see how it will behave...

**Comment by ruzickap** [comment]
I manually installed the following Windows instances and run `slmgr.vbs /dli` to see the activation details:

| Type                                     | Days     |
|------------------------------------------|----------|
| windows-10-enterprise-x64-eval           |  90 days |
| windows-server-2012_r2-standard-x64-eval | 180 days |
| windows-server-2016-standard-x64-eval    | 180 days |
| windows-server-2019-standard-x64-eval    | 180 days |

I'll try to configure the build process to create the images with similar values after `sysprep`.

**Comment by ruzickap** [comment]
I'm not sure exactly where is the problem. I tried to build Windows images with / without `SkipRearm` / `PersistAllDeviceInstalls` / `DoNotCleanUpNonPresentDevices`, but the results are not like in the table above.

For now I would like to remove `SkipRearm` #165, because it doesn't make sense to have it there.

Any advice welcome, because I'm running out of ideas.

**Comment by ruzickap** [comment]
I was able to build the images with these "activation details":

| Type                                     | Days     |
|------------------------------------------|----------|
| windows-10-enterprise-x64-eval           |  90 days |
| windows-server-2012_r2-standard-x64-eval | 180 days |
| windows-server-2016-standard-x64-eval    | 180 days |
| windows-server-2019-standard-x64-eval    | 10 days  |

It's similar to the table I created by installing Windows from the iso files - except Windows Server 2019. 

It's not possible to do sysprep of the Win2019 server and keep the 180 days trial:

https://social.technet.microsoft.com/Forums/en-US/f21b1bd9-ebe1-456b-a875-d844e03b1587/windows-server-2019-180-days-trail-issues

I'll rebuild all the images tomorrow and put them to the Vagrant Cloud.
After few days it should be visible how they behave...

**Comment by ruzickap** [comment]
I rebuilt the images and put them to Vagrant Cloud about 10 days ago. 
I started the boxes several times and `cscript C:\Windows\System32\slmgr.vbs /dli` was giving me these values every time I ran them:

| Type                                     | Days     |
|------------------------------------------|----------|
| windows-10-enterprise-x64-eval           |  90 days |
| windows-server-2012_r2-standard-x64-eval | 180 days |
| windows-server-2016-standard-x64-eval    | 180 days |
| windows-server-2019-standard-x64-eval    | 10 days  |

The changes described above helped...

Thank you for letting me know about it - I'm going to close this issue.
