### ISSUE TITLE
elevated cmd / powershell

### ISSUE THREAD

**Issue by vtraida** [ruzickap/packer-templates#16]
could you please describe how you enable elevated apps start in win 10, i cant manage start cmd, power shell start with admin privileges

**Comment by ruzickap** [comment]
Not sure what is the problem here... ?
Can you describe it better please?
Let me know what is not working...

**Comment by vtraida** [comment]
it's not a problem - in your image it works fine, can you share your solution for windows 10 - how you achieve when win + R and type  cmd - you get cmd window with administrator privileges?

**Comment by ruzickap** [comment]
Hmm... honestly I do not remember. 

Something may be in these two locations:
* https://github.com/ruzickap/ansible-role-my_common_defaults/blob/master/tasks/Win32NT-common.yml
* https://github.com/ruzickap/packer-templates/blob/763a866c956ac46ee81414f25904c789d72e6ec4/http/windows-10/Autounattend.xml#L140-L169

I'm sure I copy it from somewhere, but do not remember where...
