### ISSUE TITLE
password for user vagrant expired in widows server

### ISSUE THREAD

**Issue by wladich** [ruzickap/packer-templates#18]
I am using windows server 2016 image, version 20190405.01. 
Today, on May 17 2019 when I try to login as user vagrant  I get the message that password is expired. 
Could you please set password as "never expire" for user vagrant?

**Comment by ruzickap** [comment]
I would love to do it but I do not know how.

I'm doing it right after the installation: https://github.com/ruzickap/packer-templates/blob/master/http/windows-2016/Autounattend.xml#L174

But for some reasons after I do `sysprep` at the end I ended up again with `PasswordExpires=TRUE`.

If you know how to preserve the `PasswordExpires` attribute during+after doing `sysprep` please let me know....
