### ISSUE TITLE
Windows10s

### ISSUE THREAD

**Issue by gedw99** [ruzickap/packer-templates#2]
Could you add the new windows10s ?

At the moment it's painful because you have to first install windiws10 and then tell it to self upgrade to Windows 10s and delete itself.

**Comment by ruzickap** [comment]
It's a tricky right now. 
It's quite hard to make Ansible + WinRM + Packer working.

If you use Ansible ansible 2.4.0.0 with Fedora 27 you hit this https://github.com/ansible/ansible/issues/25298 bug when using "win_updates" module.

If you use the latest Ansible avaiable in Fedora 27 (currently 2.4.1.0) you hit another bug, where Ansible is not able to provision Windows at all:

```
windows-10-enterprise-x64-eval: fatal: [default]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Warning: Permanently added '[127.0.0.1]:39393' (RSA) to the list of known hosts.\r\n'-' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
(It's reported in github as well, but I'm not sure where)

Currently it's not possible to build latest Windows 10 with Ansible + WinRM + Packer + Qemu.

It's necessary to wait for the bugs to be fixed...

**Comment by ruzickap** [comment]
Here is another problem I saw when building latest Windows 10 with Ansible + WinRM + Packer + Qemu:
https://github.com/hashicorp/packer/issues/4904

**Comment by gedw99** [comment]
thanks @ruzickap for the follow up.

I am also hitting issue with windows 10 s on the other side in terms of packaging apps for the Windows Store...
No real info on how to take a .exe and turn it into a .appx, etc.
Infuriating company !

**Comment by ruzickap** [comment]
I regenerated all the windows images, but they do not contain the latest updates :-(

I have to disable updating the images:
https://github.com/ruzickap/packer-templates/blob/master/ansible/win.yml#L43

I need to wait for fixing this Ansible/Packer bug: hashicorp/packer#5845

Then I will be able to create fully updated Windows images...

**Comment by gedw99** [comment]
ok thanks for update !!

**Comment by ruzickap** [comment]
I changed the way how to build the Windows images using Ansible and now all images has the latest Windows updates :-)

Thanks for reporting this...
