### ISSUE TITLE
Unable to build windows 2019 standard: ansible timout value issues

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#20]
hi,

im trying to build the windows 2019 standard image and it fails due to ansible timeouts while winrm connection, even tho it manages to connect winrm beforehand:

> ==> qemu: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
> ==> qemu: Connected to WinRM!

ansible fails with the following error:

ssl: read_timeout_sec must exceed operation_timeout_sec, and both must be non-zero

i had to remove the options in the ansible call to make it work, not sure if this is related to the ansible version i am using (ansible 2.8.1)

```
diff --git a/windows.json b/windows.json
index 9b898bc..35cc4d0 100644
--- a/windows.json
+++ b/windows.json
@@ -129,7 +129,7 @@
     {
       "type": "shell-local",
       "environment_vars": "ANSIBLE_CONFIG=ansible/ansible.cfg",
-      "command": "ansible-playbook --connection=winrm --extra-vars='ansible_winrm_read_timeout_sec=1000 ansible_winrm_operation_timeout_sec=900 ansible_winrm_server_cert_validation=ignore packer_build_name={{ user `name` }} ansible_user='{{ user `winrm_username` }}' ansible_ssh_pass='{{ user `winrm_password` }}' ansible_port={{ user `ssh_winrm_host_port` }}' -i 127.0.0.1, ansible/win-simple.yml"
+      "command": "ansible-playbook --connection=winrm --extra-vars='ansible_winrm_server_cert_validation=ignore packer_build_name={{ user `name` }} ansible_user='{{ user `winrm_username` }}' ansible_ssh_pass='{{ user `winrm_password` }}' ansible_port={{ user `ssh_winrm_host_port` }}' -i 127.0.0.1, ansible/win-simple.yml"
     },
     {
       "type": "windows-shell",
```

**Comment by ruzickap** [comment]
I removed both `ansible_winrm_read_timeout_sec=1000` and `ansible_winrm_operation_timeout_sec=900` Ansible WinRM parameters.
I was not able to reproduce your issue, but windows builds are working fine without them.

Thank you
