### ISSUE TITLE
bsdtar: truncated gzip input on windows box

### ISSUE THREAD

**Issue by thigg** [ruzickap/packer-templates#21]
Vagrant box add fails on box `peru/windows-10-enterprise-x64-eval 
`:

    bsdtar -v -x -m -s "|\\\\|/|" -C ./ -f /home/user/.vagrant.d/tmp/box4d12f7d62e35648509248a6ba61a4ce8014d0be3
    x Vagrantfile
    x box.ovf
    x metadata.json
    x windows10-desktop-packer-template-1561617170-disk001.vmdk: truncated gzip input
    bsdtar: Error exit delayed from previous errors.

**Comment by ruzickap** [comment]
I'll rebuild the `peru/windows-10-enterprise-x64-eval` vagrant+libvirt images...

**Comment by thigg** [comment]
thanks a lot for the fast response

**Comment by thigg** [comment]
the problem was with the virtualbox image. You are going to rebuild that as well?

**Comment by ruzickap** [comment]
Both `peru/windows-10-enterprise-x64-eval` `{virtualbox,libvirt}` images/boxes were rebuilt.
Latest version is: `v20190704.01`
Can you please try again and let me know?

**Comment by thigg** [comment]
Yes works fine now :) thanks
