### ISSUE TITLE
remove ubuntu16 _comment line?

### ISSUE THREAD

**Issue by deargle** [ruzickap/packer-templates#226]
I know the repo does not list ubuntu1604 as supported, but nevertheless [this line](https://github.com/ruzickap/packer-templates/blob/4990e0b262fa8e78a5029f3d58e9291930745f4b/ubuntu-desktop.json#L4) suggests it _might_ be supported, but networking is not working I think because sysprep etc assumes that netplan is being used, which is default in ubuntu > 16, but not used for 16. << Long sentence!

**Comment by deargle** [comment]
Was probably a premature comment -- it's not totally broken, but there's still something wrong. I'm using vagrant-libvirt, and I'm seeing though that any additional networks are declared besides the default management one, then a box built using can't get an ip address at all. As soon as I add an entry to /etc/networking/interfaces for eth0 as dhcp though, it can get an address. I know that generic/ubuntu1604 packer build does some sysprep with /etc/network/interfaces along those lines, https://github.com/lavabit/robox/blob/master/scripts/ubuntu1604/network.sh

**Comment by deargle** [comment]
Forget it, I can't replicate consistently. I'm going to start from a clean slate, I think I have something really borked in my libvirt vir bridges.

**Comment by ruzickap** [comment]
Thank you for you comments.
 
I remember there were some problems with networking across different LTS Ubuntu versions, because they changed the "networking stacks" in almost every version. 

Let me know if the 16.04 is broken and I can look at it...

Thank you.

**Comment by deargle** [comment]
After I cleared out all my virsh networks and started afresh there, 16.04 seems to be working okay, even with an extra adapter.
