### ISSUE TITLE
windows-server-2016-standard-x64-eval (libvirt, 20190723.01) broken

### ISSUE THREAD

**Issue by jbeshay** [ruzickap/packer-templates#23]
I've just started a new VM with the latest Windows Server 2016 Standard vagrant box for libvirt:
`peru/windows-server-2016-standard-x64-eval (libvirt, 20190723.01)`

It fails to start showing the following error on the display:
<img width="1012" alt="Screen Shot 2019-07-23 at 2 37 37 PM" src="https://user-images.githubusercontent.com/12718704/61749522-d0e5ec80-ad57-11e9-842b-b0a484aaaf25.png">

**Comment by ruzickap** [comment]
Hello I was building the new images yesterday and there were some issues with this version: `20190723.01`

May I ask you to try it again with latest `20190723.01` please?

Thank you

**Comment by jbeshay** [comment]
I've just tested `peru/windows-server-2016-standard-x64-eval (libvirt, 20190724.01)`. It works fine. 

Thanks for your prompt response, @ruzickap!
