### ISSUE TITLE
[Windows 2019] Could not apply the unattend answer file <DiskConfiguration> setting

### ISSUE THREAD

**Issue by cde0** [ruzickap/packer-templates#233]
I try to run qemu for Windows 2019 but i get this error.
![image](https://user-images.githubusercontent.com/49035763/102987125-8e12e000-451a-11eb-9c30-5417ccf009b1.png)

I follow the same steps and change only the headless to true.

**Comment by ruzickap** [comment]
Thank you for letting me know. 
Unfortunately I do not have the "Linux" laptop now, but I'll rebuild the images/boxes next week.
I hope I'll be able to test it + fix it soon...
