### ISSUE TITLE
Windows 10: Winrm not configured

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#24]
hi,

The windows 10 evaluation image on vagrantcloud does not come up with vagrant because the winrm service is not configured within the image. I was starting up the VM via vagrant but it times out during winrm connection setup.

I then logged into the VM (which was obviously finished and up running just fine) and started winrm quickconfig and got:

> C:\Users\vagrant>winrm quickconfig
> WinRM is not set up to receive requests on this machine.
> The following changes must be made:
> 
> Start the WinRM service.
> 
> Make these changes [y/n]? y

so it seems the image was missing the winrm configuration and as such vagrant tries endlessly to connect the vm:

>  INFO winrm: Checking whether WinRM is ready...
> DEBUG provider: Searching for cap: winrm_info
> DEBUG provider: Checking in: libvirt
> DEBUG ssh: Checking key permissions: /home/abi/.vagrant.d/insecure_private_key
> DEBUG winrmshell: initializing WinRMShell
>  INFO winrmshell: Attempting to connect to WinRM...
>  INFO winrmshell:   - Host: 192.168.121.46
>  INFO winrmshell:   - Port: 5985
>  INFO winrmshell:   - Username: vagrant
>  INFO winrmshell:   - Transport: negotiate
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman
> DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.46:5985/wsman

It seems like other services such as RDP are not configured either.

**Comment by abbbi** [comment]
image version used:

peru/windows-10-enterprise-x64-eval (libvirt, 20190724.01)

**Comment by ruzickap** [comment]
That's strange. I tried it and it was working fine for me:

```bash
gitlab-runner@ubuntu:/var/tmp/win10$ mkdir windows-10-enterprise-x64-eval

gitlab-runner@ubuntu:/var/tmp/win10$ cd windows-10-enterprise-x64-eval

gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$ vagrant init peru/windows-10-enterprise-x64-eval
==> vagrant: A new version of Vagrant is available: 2.2.5 (installed version: 2.2.4)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$ VAGRANT_DEFAULT_PROVIDER=libvirt vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'peru/windows-10-enterprise-x64-eval' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'peru/windows-10-enterprise-x64-eval'
    default: URL: https://vagrantcloud.com/peru/windows-10-enterprise-x64-eval
==> default: Adding box 'peru/windows-10-enterprise-x64-eval' (v20190724.01) for provider: libvirt
    default: Downloading: https://vagrantcloud.com/peru/boxes/windows-10-enterprise-x64-eval/versions/20190724.01/providers/libvirt.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> default: Successfully added box 'peru/windows-10-enterprise-x64-eval' (v20190724.01) for 'libvirt'!
==> default: Uploading base box image as volume into libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              windows-10-enterprise-x64-eval_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            2048M
==> default:  -- Management MAC:
==> default:  -- Loader:
==> default:  -- Nvram:
==> default:  -- Base box:          peru/windows-10-enterprise-x64-eval
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/windows-10-enterprise-x64-eval_default.img (50G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:
==> default:  -- Initrd:
==> default:  -- Graphics Type:     spice
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        qxl
==> default:  -- Video VRAM:        9216
==> default:  -- Sound Type:    ich6
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- CHANNEL:             type=unix, mode=
==> default:  -- CHANNEL:             target_type=virtio, target_name=org.qemu.guest_agent.0
==> default:  -- CHANNEL:             type=spicevmc, mode=
==> default:  -- CHANNEL:             target_type=virtio, target_name=com.redhat.spice.0
==> default:  -- RNG device model:  random
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Forwarding ports...
==> default: 3389 (guest) => 3389 (host) (adapter eth0)
==> default: 5986 (guest) => 5986 (host) (adapter eth0)
==> default: 5985 (guest) => 5985 (host) (adapter eth0)
==> default: Configuring and enabling network interfaces...

gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$
```

I also checked the WinRM service if it is running and it was started right after boot:

![image](https://user-images.githubusercontent.com/1434387/62022359-41639200-b1cc-11e9-8295-96b655ba39a7.png)

When the windows is starting for the first time it takes about 5 minutes. 

RDP works fine as well:

```bash
gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$ vagrant rdp
==> default: Detecting RDP info...
    default: Address: 192.168.121.203:3389
    default: Username: vagrant
==> default: Vagrant will now launch your RDP client with the connection parameters
==> default: above. If the connection fails, verify that the information above is
==> default: correct. Additionally, make sure the RDP server is configured and
==> default: running in the guest machine (it is disabled by default on Windows).
==> default: Also, verify that the firewall is open to allow RDP connections.

gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$
```

**Comment by abbbi** [comment]
hi,

it seems the general bootup issue was caused by following setting in my Vagrantfile:

config.vm.communicator = "winrm"

probably the newer versions use winrm-ssl by default. After removing that statement
im able to bring up the Virtual machine until a point where i can execute the Vagrant
Powershell provisioner, which fails with some obscure Exception, but thats an issue
not related to this BR:

```
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
    default: (10,8):UserId:
    default: At line:72 char:1
    default: + $folder.RegisterTaskDefinition($task_name, $task, 6, $username, $pass ...
    default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    default:     + FullyQualifiedErrorId : System.ArgumentException
    default: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    default: At line:74 char:1
    default: + $registered_task = $folder.GetTask("\$task_name")
    default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    default:     + FullyQualifiedErrorId : System.IO.FileNotFoundException
    default: You cannot call a method on a null-valued expression.
    default: At line:75 char:1
    default: + $registered_task.Run($null) | Out-Null
    default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    default:     + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by abbbi** [comment]
Thats actually:

 https://github.com/clong/DetectionLab/issues/172

**Comment by ruzickap** [comment]
Can you please repeat the same steps I did in my previous post to be able to compare the outputs?

Meanwhile I'll upgrade my Vagrant installation to the latest version and test it again.

Thank you...

**Comment by marcindulak** [comment]
Have a very similar problem: `vagrant up` hangs at `Waiting for SSH to become available`. I must say I've never used any of your boxes before.

```
cat /etc/*release | grep VERSION=
VERSION="18.04.3 LTS (Bionic Beaver)"
```

```
vagrant version
Installed Version: 2.2.5
```

```
vagrant plugin list
vagrant-libvirt (0.0.45, global)
```

```
vboxmanage --version
5.2.32r132073
```

```
for net in `virsh -q net-list --all | awk '{print $1}'`; do virsh net-destroy $net; done
virsh net-autostart default --disable
for p in `ps aux | grep libv | grep -v grep | awk '{print $1, $2}' | grep $USER | awk '{print $2}'`; do echo kill $p&& kill $p; done
for pool in `virsh -q pool-list | awk '{print $1}'`; do virsh pool-destroy $pool; virsh pool-undefine $pool; done
for guest in `virsh -q list --inactive | awk '{print $2}'`; do virsh undefine $guest; done
```

```
cat Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define 'windows' do |machine|
    machine.vm.box = 'peru/windows-10-enterprise-x64-eval'
    machine.vm.box_url = machine.vm.box
    machine.vm.provider 'libvirt' do |p|
      p.memory = 1536  # Windows is greedy
      p.cpus = 1
    end
  end
end
```
```
VAGRANT_LOG=debug VAGRANT_DEFAULT_PROVIDER=libvirt vagrant up
...
==> windows: Starting domain.
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x0000000002af5fd0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x0000000002af5f58>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x0000000002af5f30>
DEBUG wait_till_up: Searching for IP for MAC address: 52:54:00:bf:c8:2b
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> windows: Waiting for domain to get an IP address...
==> windows: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO wait_till_up: Got IP address 192.168.121.223
 INFO wait_till_up: Time for getting IP: 27.34371829032898
 INFO interface: info: Waiting for SSH to become available...
 INFO interface: info: ==> windows: Waiting for SSH to become available...
==> windows: Waiting for SSH to become available...
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: libvirt
DEBUG ssh: Checking key permissions: /home/ubuntu/.vagrant.d/insecure_private_key
DEBUG winrmshell: initializing WinRMShell
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 192.168.121.223
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: negotiate
DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.223:5985/wsman
DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.223:5985/wsman
DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.223:5985/wsman
...
```

**Comment by marcindulak** [comment]
Well, eventually it works, it seems it just takes a long time, a couple of minutes.

**Comment by marcindulak** [comment]
As for the powershell issue, I'm also experiencing it with this box https://github.com/ruzickap/packer-templates/issues/27

**Comment by ruzickap** [comment]
First start of the Windows image (after `sysprep`) is always really slow. It may take about 5 minutes - there is not much I can do with it, because that's how it is designed.

All other windows (re)starts should be fine and should be reasonable fast.

**Comment by marcindulak** [comment]
For me also the consequent `vagrant reload` are slow during `Waiting for SSH to become available`. I see in `c:\windows\system32\sysprep\panther\setuperr.log` this run does not involve sysprep.
I can't find an SSH server on the box OS, and after the box finishes booting, a subequent `vagrant ssh` hangs.

What is performing `Waiting for SSH to become available`? Maybe this just times out?

I see a maybe relevant discussion at https://github.com/gusztavvargadr/packer/issues/101

**Comment by marcindulak** [comment]
By the way `Waiting for SSH to become available` comes from https://github.com/vagrant-libvirt/vagrant-libvirt/issues/635

**Comment by nishtsh1** [comment]
IS this issue still open? I am facing same opening remote shell issue

**Comment by nishtsh1** [comment]
> That's strange. I tried it and it was working fine for me:
> 
> ```shell
> gitlab-runner@ubuntu:/var/tmp/win10$ mkdir windows-10-enterprise-x64-eval
> 
> gitlab-runner@ubuntu:/var/tmp/win10$ cd windows-10-enterprise-x64-eval
> 
> gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$ vagrant init peru/windows-10-enterprise-x64-eval
> ==> vagrant: A new version of Vagrant is available: 2.2.5 (installed version: 2.2.4)!
> ==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html
> 
> A `Vagrantfile` has been placed in this directory. You are now
> ready to `vagrant up` your first virtual environment! Please read
> the comments in the Vagrantfile as well as documentation on
> `vagrantup.com` for more information on using Vagrant.
> 
> gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$ VAGRANT_DEFAULT_PROVIDER=libvirt vagrant up
> Bringing machine 'default' up with 'libvirt' provider...
> ==> default: Box 'peru/windows-10-enterprise-x64-eval' could not be found. Attempting to find and install...
>     default: Box Provider: libvirt
>     default: Box Version: >= 0
> ==> default: Loading metadata for box 'peru/windows-10-enterprise-x64-eval'
>     default: URL: https://vagrantcloud.com/peru/windows-10-enterprise-x64-eval
> ==> default: Adding box 'peru/windows-10-enterprise-x64-eval' (v20190724.01) for provider: libvirt
>     default: Downloading: https://vagrantcloud.com/peru/boxes/windows-10-enterprise-x64-eval/versions/20190724.01/providers/libvirt.box
>     default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
> ==> default: Successfully added box 'peru/windows-10-enterprise-x64-eval' (v20190724.01) for 'libvirt'!
> ==> default: Uploading base box image as volume into libvirt storage...
> ==> default: Creating image (snapshot of base box volume).
> ==> default: Creating domain with the following settings...
> ==> default:  -- Name:              windows-10-enterprise-x64-eval_default
> ==> default:  -- Domain type:       kvm
> ==> default:  -- Cpus:              1
> ==> default:  -- Feature:           acpi
> ==> default:  -- Feature:           apic
> ==> default:  -- Feature:           pae
> ==> default:  -- Memory:            2048M
> ==> default:  -- Management MAC:
> ==> default:  -- Loader:
> ==> default:  -- Nvram:
> ==> default:  -- Base box:          peru/windows-10-enterprise-x64-eval
> ==> default:  -- Storage pool:      default
> ==> default:  -- Image:             /var/lib/libvirt/images/windows-10-enterprise-x64-eval_default.img (50G)
> ==> default:  -- Volume Cache:      default
> ==> default:  -- Kernel:
> ==> default:  -- Initrd:
> ==> default:  -- Graphics Type:     spice
> ==> default:  -- Graphics Port:     -1
> ==> default:  -- Graphics IP:       127.0.0.1
> ==> default:  -- Graphics Password: Not defined
> ==> default:  -- Video Type:        qxl
> ==> default:  -- Video VRAM:        9216
> ==> default:  -- Sound Type:    ich6
> ==> default:  -- Keymap:            en-us
> ==> default:  -- TPM Path:
> ==> default:  -- INPUT:             type=mouse, bus=ps2
> ==> default:  -- CHANNEL:             type=unix, mode=
> ==> default:  -- CHANNEL:             target_type=virtio, target_name=org.qemu.guest_agent.0
> ==> default:  -- CHANNEL:             type=spicevmc, mode=
> ==> default:  -- CHANNEL:             target_type=virtio, target_name=com.redhat.spice.0
> ==> default:  -- RNG device model:  random
> ==> default: Creating shared folders metadata...
> ==> default: Starting domain.
> ==> default: Waiting for domain to get an IP address...
> ==> default: Waiting for SSH to become available...
> ==> default: Forwarding ports...
> ==> default: 3389 (guest) => 3389 (host) (adapter eth0)
> ==> default: 5986 (guest) => 5986 (host) (adapter eth0)
> ==> default: 5985 (guest) => 5985 (host) (adapter eth0)
> ==> default: Configuring and enabling network interfaces...
> 
> gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$
> ```
> 
> I also checked the WinRM service if it is running and it was started right after boot:
> 
> ![image](https://user-images.githubusercontent.com/1434387/62022359-41639200-b1cc-11e9-8295-96b655ba39a7.png)
> 
> When the windows is starting for the first time it takes about 5 minutes.
> 
> RDP works fine as well:
> 
> ```shell
> gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$ vagrant rdp
> ==> default: Detecting RDP info...
>     default: Address: 192.168.121.203:3389
>     default: Username: vagrant
> ==> default: Vagrant will now launch your RDP client with the connection parameters
> ==> default: above. If the connection fails, verify that the information above is
> ==> default: correct. Additionally, make sure the RDP server is configured and
> ==> default: running in the guest machine (it is disabled by default on Windows).
> ==> default: Also, verify that the firewall is open to allow RDP connections.
> 
> gitlab-runner@ubuntu:/var/tmp/win10/windows-10-enterprise-x64-eval$
> ```

I am facing same issue in ubuntu20.04. After default 20 tries VM disconnects. Any resolution for this?
Vagrantfile is:
#Set the machine name
$machineName="WIN10"

Vagrant.require_version ">= 1.7.0"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.hostname=$machineName
  config.vm.network "private_network", type: "dhcp"
  config.vm.define $machineName do |t|
    t.vm.host_name=$machineName
    config.vm.provider :libvirt do |v|
      v.memory = 8192
      v.cpus = 6
    end
  end
end

**Comment by ruzickap** [comment]
Hello. 

I was looking at it and the `vagrant winrm` is not working.

`vagrant winrm-config` seems to give me something:

```
vagrant winrm-config
Host default
  HostName 192.168.121.5
  User vagrant
  Password vagrant
  Port 5985
  RDPHostName 192.168.121.5
  RDPPort 3389
  RDPUser vagrant
  RDPPassword vagrant
```

Do you have some way how to test the winrm "outside" the vagrant ?

`vagrant ssh` is working...

**Comment by nishtsh1** [comment]
Any specific network configurations to do in Windows 10 VM for WinRM?

**Comment by nishtsh1** [comment]
This page isn’t working right now when tried http://l;ocalhost:5985/wsman on Windows 10 Guest OS. Any clue why wsman is not working?

**Comment by nishtsh1** [comment]
telnet works, vagrant ssh works, Enter-PSSession also works but vagrant winrm doesn't work. Unable to find any clue irrespective of setting all WinRM configurations
