### ISSUE TITLE
Enable WInRM plaintext authentication

### ISSUE THREAD

**Issue by autrimpo** [ruzickap/packer-templates#25]
Hi,

would it be possible to enable `:plaintext` authentication for WinRM on Windows images by default?
(`winrm set winrm/config/service '@{AllowUnencrypted="true"}'`)

The default `:negotiate` method breaks when trying to set up an Active Directory Domain Controller (see [here](https://github.com/rgl/windows-domain-controller-vagrant/blob/master/Vagrantfile#L6) and [here](https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4)).

**Comment by ruzickap** [comment]
It should not be a problem to add it.

Do you know if there is any way how to do it via changing the registry ?
(or powershell) ?

Thank you...

**Comment by autrimpo** [comment]
I don't know about registry, but the `winrm set…` command in my original comment is for powershell.

**Comment by ruzickap** [comment]
I will update the images next week and as you for testing it...

**Comment by autrimpo** [comment]
I just tried the new images, everything works great!
Thank you.
