### ISSUE TITLE
virtualbox not supported for windows-server-2016-standard-x64-eval 

### ISSUE THREAD

**Issue by mburtless** [ruzickap/packer-templates#259]
The virtualbox provider no longer seems to be supported for windows-server-2016-standard-x64-eval.  This is reflected in the providers section of the [vagrant](https://app.vagrantup.com/peru/boxes/windows-server-2016-standard-x64-eval) page.

I'm just wondering if this is expected.  Will only libvirt be supported for Win 2016 moving forward?

Thanks!

**Comment by ruzickap** [comment]
I will look at it...

**Comment by ruzickap** [comment]
I'm sorry - I tried it several time to build the `windows-server-2016-standard-x64-eval` image using GitHub Action and it always failed. 
When I did it on my local laptop it was working every time...

You can build the image yourself using the `build.sh windows-server-2016-standard-x64-eval-virtualbox` until I find the way how to properly automate it using GH Actions.

**Comment by mburtless** [comment]
Hi @ruzickap - No worries, thanks so much for trying to get this working!

**Comment by ZloeSabo** [comment]
I was investigating the vagrant image build issue, and it seems that the problem is that GitHub actions simply have no support for nested virtualization (see actions/virtual-environments#183) that VirtualBox requires. As the GH team has no plans to support that, the best option would perhaps be to move pipelines to some other CI (did the project use Travis before?).

**Comment by ruzickap** [comment]
Yes it's true. But the GitHub MacOS instances do support nested virtualization. All my images are built there (and most of them successfully).

I used Travis long time ago, but I'm not sure if they support nested virtualization.

The biggest problem I see with all the 3rd party CI tools is that it's not easy the debug problems when they appear. 

You can not connect to 3rd party CI virtual machine failed build to see the errors, debug them, connect to Qemu/VirtualBox, ... 

If you build the images locally on the laptop - you can get inside the failed VM and debug the failed OS installation.
