### ISSUE TITLE
Can't build windows image

### ISSUE THREAD

**Issue by peterwi** [ruzickap/packer-templates#278]
This is the error
`qemu: Error creating temporary file for CD: error creating new directory /var/tmp/packer_to_cdrom905166983/virtio-win/Balloon: mkdir /var/tmp/packer_to_cdrom905166983/virtio-win/Balloon: permission denied`

**Comment by ruzickap** [comment]
Are you using latest packer `1.7.2` ?
I saw this error in some older packer versions...

**Comment by peterwi** [comment]
packer --version 1.7.2

**Comment by peterwi** [comment]
I looked at https://github.com/ruzickap/packer-templates/pull/212
and then added this
`test -d "${VIRTIO_WIN_ISO_DIR}" || xorriso -report_about SORRY -osirrox on -indev "${VIRTIO_WIN_ISO}" -find . -type d -exec chmod u+rwx -- -extract / "${VIRTIO_WIN_ISO_DIR}"
        fi
      ;;
      *)
`
to build.sh, working ok now.
