### ISSUE TITLE
Port forwarding not working for Windows with libvirt

### ISSUE THREAD

**Issue by FlxPeters** [ruzickap/packer-templates#279]
Hey and thanks for your awesome work.

I try to forward the ~~RDP~~ WinRM ports of a Windows machine from a Ubuntu 20.04 machine running QEMU and Vagrant with libvirt plugin like explained in the Readme of the box: https://app.vagrantup.com/peru/boxes/windows-server-2019-standard-x64-eval

I use a plain Vagrant file like `vagrant init peru/windows-server-2019-standard-x64-eval` creates.
The box starts as expected, but port forwarding does not work.

Connecting RDP/WinRM via the Box IP works, but i need to contact the box from localhost because my test scripts cannot determinate the IP of the Vagrant box and rely on a port forwarding. 

After some debugging i found out, that the SSH tunnel from my local machine to the Vagrant box is broken: 
```
==> .vagrant/machines/default/libvirt/logs/ssh-forwarding-*_5985-192.168.121.143_5985.log <==
ssh: connect to host 192.168.121.143 port 22: Connection timed out
```
Is this a known limitation of Windows with the Vagrant Libvirt provider?
I couldn't find any SSH server running in Windows. I therefore suspect that it cannot work at all but i want to make sure this is correct.

**Comment by ruzickap** [comment]
Hello.

I'm quite sure this was working (RDP and WinRM) in the past. 
Unfortunately I do not have linux laptop to test / troubleshoot it :-(

I remember - it was a pain to make WinRM working with libvirt, but it should be possible.

I'm using `openssh` for windows in one of my builds:
 
https://github.com/ruzickap/ansible-role-my_common_defaults/blob/51a37e42498d293cf9a44e859630b6beebf708cf/tasks/Win32NT-common.yml#L8

I'm sorry but I can not help you with Linux + libvirt issues right now...
