### ISSUE TITLE
Shared folder by default

### ISSUE THREAD

**Issue by marcindulak** [ruzickap/packer-templates#28]
It looks to me that https://app.vagrantup.com/peru/boxes/windows-10-enterprise-x64-eval/versions/20190802.01 does not mount the current folder in the guest.

```
Vagrant.configure(2) do |config|
  config.vm.define 'windows' do |machine|
    machine.vm.box = 'peru/windows-10-enterprise-x64-eval'
    machine.vm.box_url = machine.vm.box
    machine.vm.provider 'libvirt' do |p|
      p.memory = 1536  # Windows is greedy
      p.cpus = 1
    end
  end
end
```

By default vagrant linux boxes share the current folder (where Vagrantfile is located) under `/vagrant` https://www.vagrantup.com/docs/synced-folders/, and windows boxes share it typically under `c:\vagrant`. The linux distributions that don't include VirtualBox Guest Additions, like Fedora/RHEL, offer other ways of sharing the folder https://fedoramagazine.org/vagrant-sharing-folders-vagrant-sshfs/.

What are the available/preferred solutions for your boxes? Can the `vagrant` folder be mounted automatically?

**Comment by ruzickap** [comment]
Actually there is no "automatic" mounting the current directory to `c:\vagrant` configured in the Windows images.

If you have some description - how this can be configured using powershell or commands or "regedit" in windows - I can add it.

In the current images you need to configure it manually for now...
