### ISSUE TITLE
VMs hang on "Waiting for machine to reboot..."

### ISSUE THREAD

**Issue by manero6** [ruzickap/packer-templates#288]
Hi,

first of all thanks for the amazing boxes! Thanks to them I'm saving myself a loooot of tiime :)

I have this issue with the Windows 10 Enterprise box.
Most of the time it works as expected, but sometimes it hangs on "Waiting for machine to reboot..." and it's not able to continue, I have then to CTRL-C.

Waiting time goes above 15-20 minutes.

In a multi-machine Vagrantfile it could happen that a few complete "vagrant up" correctly while other hang.

Do you have already encounter this problem?

**Comment by ruzickap** [comment]
Hello.

I rebuilt the images - can you please try it again?
Can you tell me if you are using the Virtualbox or libvirt of Windows 10 Enterprise?

**Comment by manero6** [comment]
Hi again,

I'm using it 95% of the time with libvirt.
It seems that the newly built image fixed the issue!! thanks a lot :)

[This Vagratfile](https://github.com/manero6/ansible-for-gfz/blob/main/vagrant/windows/example%204/example4_peru-win10/Vagrantfile)

old image:

```
time vagrant up

...
==> windows-2: Setting hostname...
==> windows-3: Setting hostname...
==> windows-1: Setting hostname...
==> windows-2: Waiting for machine to reboot...
==> windows-3: Waiting for machine to reboot...
==> windows-1: Waiting for machine to reboot...
==> windows-2: Forwarding ports...
==> windows-2: 3389 (guest) => 3389 (host) (adapter eth0)
==> windows-2: 5986 (guest) => 5986 (host) (adapter eth0)
==> windows-2: 5985 (guest) => 5985 (host) (adapter eth0)
==> windows-2: Configuring and enabling network interfaces...
^C==> windows-1: Waiting for cleanup before exiting...
^C==> windows-1: Exiting immediately, without cleanup!

real	35m44,404s
user	0m5,374s
sys	0m0,590s
```

new image:

```
time vagrant up

...
==> windows-2: Setting hostname...
==> windows-3: Setting hostname...
==> windows-1: Setting hostname...
==> windows-2: Waiting for machine to reboot...
==> windows-3: Waiting for machine to reboot...
==> windows-1: Waiting for machine to reboot...
==> windows-3: Forwarding ports...
==> windows-3: 3389 (guest) => 3389 (host) (adapter eth0)
==> windows-3: 5986 (guest) => 5986 (host) (adapter eth0)
==> windows-3: 5985 (guest) => 5985 (host) (adapter eth0)
==> windows-3: Configuring and enabling network interfaces...
==> windows-2: Forwarding ports...
==> windows-2: 3389 (guest) => 3389 (host) (adapter eth0)
==> windows-2: 5986 (guest) => 5986 (host) (adapter eth0)
==> windows-2: 5985 (guest) => 5985 (host) (adapter eth0)
==> windows-2: Configuring and enabling network interfaces...
==> windows-1: Forwarding ports...
==> windows-1: 3389 (guest) => 3389 (host) (adapter eth0)
==> windows-1: 5986 (guest) => 5986 (host) (adapter eth0)
==> windows-1: 5985 (guest) => 5985 (host) (adapter eth0)
==> windows-1: Configuring and enabling network interfaces...

real	8m1,260s
user	0m5,577s
sys	0m0,825s
```

**Comment by ruzickap** [comment]
Yes... Testing the Windows images is not easy and there are sometimes problems during the build which can not be detected.

Always use latest images - I'll try to fix/rebuild them if they are be broken.
