### ISSUE TITLE
Libvirt: Set HyperV Related Feature settings for windows by default?

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#29]
hi,

libvirt has some settings that can have good impact on windows performance on libvirt. I have been looking into these and after investigation i can tell that these options do indeed bring some performance speedup. Currently vagrant-libvirt has an issue where setting of multiple options in regards to hyperv features fails, see:

https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1039

but as this is sorted out i think it would make sense to define the following options in the default
Vagrantfile for all windows boxes:

```
       domain.hyperv_feature :name => 'stimer', :state => 'on'
         domain.hyperv_feature :name => 'relaxed', :state => 'on'
         domain.hyperv_feature :name => 'vapic', :state => 'on'
         domain.hyperv_feature :name => 'synic', :state => 'on'
 
```

During my tests these settings could speed up a first bootup of the windows VM at roughly about 10 seconds

```
with settings (vagrant up of windows 2016 standard image)
real    1m49,131s
real    1m42,969s
real    1m42,747s
without:
real    2m4,707s
real    2m8,940s
real    2m4,755s
```

**Comment by abbbi** [comment]
There is also another libvirt timer setting "hypervclock" which would make sense to support, but currentla vagrant-libvirt is missing support for that, im working on that. Some windows versions are known to eat up about 25% of the Virtual CPU while beeing totally idle, this issue is realted to timer synchronization issues.

**Comment by ruzickap** [comment]
Good point.
I'll check it and let you know - but it seems like a good idea.

**Comment by ruzickap** [comment]
I added the `hyperv_feature` lines into the "windows Vagrantfile".
The new images containing the `hyperv` options will be ready in few days...

**Comment by ruzickap** [comment]
May I ask you to try one of the latest "win" image - the `hyperv_feature` should be there...

Thank you.

**Comment by netoarmando** [comment]
After those changes I started to hit the following error:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Libvirt Provider:
* The following settings shouldn't exist: hyperv_feature
```
Version used:
```
peru/windows-server-2016-standard-x64-eval (libvirt, 20190905.01)
```
```
$ vagrant --version
Vagrant 2.0.2

$ vagrant plugin list
vagrant-libvirt (0.0.40, system)
vagrant-sshfs (1.3.1, system)
winrm (2.3.2)
winrm-elevated (1.1.1)
winrm-fs (1.3.2)
```

**Comment by ruzickap** [comment]
Looks like you need a newer versions of the tools:

I'm using:

```
$ vagrant --version
Vagrant 2.2.5

$ vagrant plugin list
vagrant-libvirt (0.0.45, global)
```

I guess you need to use the higher version for plugin `vagrant-libvirt` for sure.

Can you please try to upgrade and let me know?

**Comment by jbeshay** [comment]
I started getting the following error with the `20191001.01` image. 

`Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unsupported configuration: unsupported HyperV Enlightenment feature: stimer`

```
# vagrant box list
peru/windows-server-2016-standard-x64-eval (libvirt, 20191001.01)
# vagrant --version
Vagrant 2.2.5
# vagrant plugin list
vagrant-libvirt (0.0.45, global)
vagrant-proxyconf (2.0.6, global)
# dpkg -s libvirt-bin
Package: libvirt-bin
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 10642
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: libvirt
Version: 1.3.1-1ubuntu10.27
```

Could you please elaborate on the versions that need to be used?

**Comment by ruzickap** [comment]
Hello.

Here is my configuration:

```
$ vagrant box list
peru/windows-server-2016-standard-x64-eval (libvirt, 20191001.01)

$ vagrant --version
Vagrant 2.2.5

$ vagrant plugin list
vagrant-libvirt (0.0.45, global)

$ libvirtd --version
libvirtd (libvirt) 4.0.0

$ dpkg -l | grep -E "(vagrant|libvirt-bin)"
ii  libvirt-bin                           4.0.0-1ubuntu8.12                               amd64        programs for the libvirt library
ii  vagrant                               1:2.2.5                                         amd64        no description given

$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Ubuntu 18.04.3 LTS"
```

Can you please try to update the libvirt version? 

Thank you

**Comment by jbeshay** [comment]
Thanks for the update. Doesn't seem I can upgrade to libvirt 4.0.0 on Ubuntu 16.04 which I am using. My workaround so far is to remove this line:
`libvirt.hyperv_feature :name => 'stimer', :state => 'on'`
from the box's Vagrantfile at:
`~/.vagrant.d/boxes/peru-VAGRANTSLASH-windows-server-2016-standard-x64-eval/20191001.01/libvirt/Vagrantfile`

**Comment by ruzickap** [comment]
Good to know...
Thank you...
