### ISSUE TITLE
license eval running out in box image?

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#3]
hi,

i have been playing around with your windows  boxes since a few days and i just noted that the eval license is running out in around 167 days, that should match the date since have released the latest box version.

Was the box once bootet? As far as i know, in a correctly sysprepped image the evaluation should start from 180 days if you freshly deploy the image and it boots for the first time?

**Comment by ruzickap** [comment]
It looks like forgot to do the sysprep.

Is it enough to run something like after at the end of the build:

```
c:\windows\system32\sysprep\sysprep.exe /generalize /oobe /shutdown /unattend:a:\Autounattend.xml
```

or is it better to use PowerShell ?

```
Start-Process -FilePath $sysprepPath -ArgumentList ("/oobe /quit /generalize /unattend:a:\Autounattend.xml") -Wait -NoNewWindow
```

**Comment by abbbi** [comment]
hi,
yes, as you noted you have not run any sysprep on the last images. The first solution is the one i used for my internal images, i dont think there is the need of running it via powershell.

**Comment by ruzickap** [comment]
I tried to rebuild the Win10 with sysprep running this command:

`
C:\\Windows\\System32\\Sysprep\\sysprep.exe /generalize /oobe /quiet /unattend:C:\\Autounattend.xml
`

I used the the same [Autounattend.xml](https://github.com/ruzickap/packer-templates/blob/master/http/windows-10/Autounattend.xml) for sysprep (`C:\\Autounattend.xml`) as I used for the automated installation.

The build completed fine, but for some strange reason Windows complains about error when booting:

![image](https://user-images.githubusercontent.com/1434387/33876547-252777b6-df26-11e7-918a-26f524d4bc06.png)

I'm not very good in writing `Autounattend` files for Windows and I was not able to find the exact problem.

I'll look at it later but for now `sysprep` is not working correctly with [Autounattend.xml](https://github.com/ruzickap/packer-templates/blob/master/http/windows-10/Autounattend.xml).

**Comment by abbbi** [comment]
my shtudown command is:

shutdown_command": "c:/windows/system32/sysprep/sysprep.exe /generalize /oobe /shutdown /unattend:c:\\install\\configure.xml",

and my configure.xml looks like:

http://www.grinser.de/~abi/configure.xml

(REMOVED is the stuff internal i have removed from the file)

**Comment by ruzickap** [comment]
I created new images using sysprep.
Please let me know if it's fine now...
Thank you

**Comment by abbbi** [comment]
i there,

i just deployed a box with our new server 2012 template and it looks good. Licence Eval Timeout is in 180 Days, Thats what i would have expected beforehand too :)

**Comment by ruzickap** [comment]
With sysprep - things are much easier - thank you for showing me the "right path". 

Currently all Windows images do not contain the latest updates :-( 

I have to disable updating the images:
https://github.com/ruzickap/packer-templates/blob/master/ansible/win.yml#L43

I need to wait for fixing this bug: https://github.com/hashicorp/packer/issues/5845

Then I will be able to create fully updated Windows images...

**Comment by abbbi** [comment]
hi,

it seems this issue is back since some time, i noticed a few months ago but just came around it again. If a freshly added libvirt box is spinned up, the license eval is already starting to run out since you have released the new versions .. It works out as you are releasing a new version within that timeframe, but once you stop, the boxes will become unusable after 180 days :)

I just tried with the most recent 2016 box ('peru/windows-server-2016-standard-x64-eval' (v20200803.01) for libvirth
The 2019 boxes seem to be OK, the evaluation starts at 180 days after fresh spinup.
For the 2016 boxes its already down to 177 days.

**Comment by ruzickap** [comment]
Let's move the discussion to #158.
