### ISSUE TITLE
Server 2022

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#300]
hi,

any plans for relasing a vagrant image for server 2022?
It seems there is at least one other project that does so:

 https://github.com/jborean93/packer-windoze

**Comment by ruzickap** [comment]
Yeah... I saw it here as well: https://github.com/StefanScherer/packer-windows/pull/296/files
I will look at it in spare time...

**Comment by ruzickap** [comment]
Yes - I'm just looking at it and it seems like installation of Win Server 2022 should is quite similar to Win Server 2019.

I'll do few tests and prepare the new code + builds for Win Server 2022...

**Comment by ruzickap** [comment]
It should be ready: https://app.vagrantup.com/peru/boxes/windows-server-2022-standard-x64-eval
Please test and let me know...

**Comment by abbbi** [comment]
seems to work nicely! Thanks for your work again!
