### ISSUE TITLE
Disable Windows Auto Update?

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#32]
hi there,

recently i wondered about a bit how much Memory my Windows boxes are using, up to the point where a Vagrant VM with 3.5 GB of RAM went OOM with some applications.

Apparently it was the "svchost.exe" Process within the Vagrant VM which consumed 2.6 GB of my Main memory.

It turns out the automatic update process from windows seems to be the one running wild, while scanning the system for updateable components. I managed to get the system down to a regular Memory usage by disabling the windows auto update service:

 sc.exe config wuauserv start= disabled
 sc.exe stop wuauserv

I think this is also possible using registry, see:

 https://www.experts-exchange.com/questions/27652474/how-to-prevetn-sysprep-to-turn-automatic-update-back-on.html

maybe it would make sense to disable it during sysprep phase?

**Comment by ruzickap** [comment]
Hello.

I do not think disabling "autoupdate" is a good idea. I would prefer to find a cause - why it take so much memory.
Unfortunately I'm not a windows expert, so I can not do much with it, but disabling "autoupdate" is not a way to go. 

If you will find another way how to make `svchost.exe` to behave "normal", please let me know...

Thanks.
