### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#326]
hi,

Windows 11 seems to be available too.. would be great to have images for it :)

**Comment by ruzickap** [comment]
No issue with that... Can you share the link to the official Windows 11 Evaluation ISO file? Like it is for example for these Windows images:

https://github.com/ruzickap/packer-templates/blob/149aac20697e8a0b451a006ef8803c76cd3afc06/windows.json#L2-L6

Thank you...

**Comment by abbbi** [comment]
hm.. seems its only available via insider preview or msdn at the moment...

**Comment by ruzickap** [comment]
Ok... If it is not available yet, than there is not much to do...

**Comment by abbbi** [comment]
hi ..

I actually gave this a try with the most recent insider release building for libvirt, my findings so far:

* disk space has to be at least 64 GB
* It seems, at least the insider images require the system to have a tpm device,
and if not present, the installation will fail with according error message that windows is not supported on this platform :)

There are workarounds for qemu using a software based tpm emulator, like described here:

https://www.tecklyfe.com/how-to-create-a-windows-11-virtual-machine-in-qemu/

**Comment by abbbi** [comment]
I was able to workaround the sysprep issue by removing the onedrivesync appx package:

![sysprep2](https://user-images.githubusercontent.com/3919561/135927456-39aa0833-79e8-4637-a6ba-a8ef3584f17f.jpg)

Really, microsoft, i want to pull my hair, each time i touch that stuff ;)

**Comment by ruzickap** [comment]
I was looking at Windows 11 (https://github.com/ruzickap/packer-templates/tree/windows-11), but there are compatibility issues with VirtualBox. 
Oracle is saying that new VirtualBox should be released before end of the month with Win 11 support.

I'll wait for new VirtualBox and then come back to Windows 11 works...

Once I will have the VirtualBox Windows 11 boxes completed I'll start to look for libvirt/qemu.

**Comment by abbbi** [comment]
yeah, i think they are working on TPM support. Guess its safe to say its going to be mandatory for Virtual Machines too, on Windows 11..,

**Comment by abbbi** [comment]
.. stale bot reminder :)

**Comment by abbbi** [comment]
hm.. anything new on this? would love to see official windows 11 images.

**Comment by chp-io** [comment]
There are now examples of Windows 11 boxes that are available. However, none with the `Libvirt` provider. @ruzickap is this something that you would be interested in supporting?

**Comment by ruzickap** [comment]
Hello.

Yes it is still the plan, but I would like to do Windows 11 "libvirt" + "VirtualBox" together.
Actually you can not install Windows 11 to VirtualBox without doing some "hacky" things.
I would like to wait for VirtualBox official Windows 11 support and look at it with libvirt...

**Comment by abbbi** [comment]
For those interested, i just had to rebuild my internal boxes for libvirt recently and now winrm might fail to configure because the network interface detected during packer build is configured as public. One additional step required during ansible provisoining:

  - name: Set network type to private
      win_shell: Set-NetConnectionProfile -NetworkCategory Private

**Comment by abbbi** [comment]
Just a year later i had to re-build the images because provisioning all of a sudden failed, the detailed reason is described here:
 
https://github.com/hashicorp/vagrant/issues/12922

It seems windows 11 sometimes pulls an update during bootup that resets user information and makes it behave
as the user did never login.  After re-creating the image and sysprepping again with all updates applied it works...
