### ISSUE TITLE
setting PACKER_CACHE dir might break windows builds for libvirt

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#328]
hi,

while attempting to build an windows 11 image the installation failed because the disk settings could not be applied.
Turns out one cause for the issue was that i set another cache dir via:

`export PACKER_CACHE_DIR=/home/abi/tmp`

The problem is that on the virtual disk device with the virtio drivers, the virtio drivers then end up in:

`<device_name>:/home/abi/tmp/virtio-win/*`

instead of

`<device_name>:/virtio-win/*`

as such the path set in the Autounattend.xml doesnt match and the windows installer is unable to find the required device drivers.

**Comment by ruzickap** [comment]
I was looking at Windows 11 (https://github.com/ruzickap/packer-templates/tree/windows-11), but there are compatibility issues with VirtualBox. 
Oracle is saying that new VirtualBox should be released before end of the month with Win 11 support.

I'll wait for new VirtualBox and then come back to Windows 11 works...
