### ISSUE TITLE
Windows build might get stuck during reboot

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#329]
hi,

the ansible definition looks like:

```-    - name: Install windows updates
-      win_updates:
[..]
     - name: Windows reboot
       win_reboot:
         reboot_timeout: 10000
-      when: windows_updates.reboot_required and allow_windows_reboot_during_win_updates
```
Ive come accross situations where the system wouldnt reboot at all, because the when statement is not
met. Probably if there werent any updates to fetch prior to the reboot (could happen on newer installations
because the installer fetches the updates anyway). So it makes probably sense to skip the update
installation on newer windows releases anyway?

**Comment by ruzickap** [comment]
I partiality agree with your statement. 

Actually if I installed "any stable" operating system (form ISO), then after installation was completed there were always some new updates/security fixes/patches/ ...

I would like to find out the real cause - why the system was not rebooted. 
Can you hare some more details to allow me to reproduce the issue?
