### ISSUE TITLE
Libvirt artifact missing

### ISSUE THREAD

**Issue by salanki** [ruzickap/packer-templates#339]
Hello,

It seems as the latest build is missing the `libvirt` artifact: https://app.vagrantup.com/peru/boxes/ubuntu-20.04-server-amd64. Is it possible to kick off a new build with this included? I regretfully don't have older versions cached and it seems as they don't exist on vagrant cloud either.

**Comment by salanki** [comment]
Is it possible to kick off maybe a brand new build and see if it resolves it?

**Comment by ruzickap** [comment]
Can you try it one more time please?

Thank you...

**Comment by salanki** [comment]
This one is still broken for us, the VM never properly comes up:
```
2021/11/16 16:26:37 packer-builder-vagrant plugin: [vagrant driver] stdout: ==> source:  -- RNG device model:  random
2021/11/16 16:26:37 packer-builder-vagrant plugin: [vagrant driver] stdout: ==> source: Creating shared folders metadata...
2021/11/16 16:26:37 packer-builder-vagrant plugin: [vagrant driver] stdout: ==> source: Starting domain.
2021/11/16 16:26:38 packer-builder-vagrant plugin: [vagrant driver] stdout: ==> source: Waiting for domain to get an IP address...
```

**Comment by ruzickap** [comment]
I'm sorry, but I can not troubleshoot it now. 
I need to get some Linux laptop first, because it will not work on my MacOS.

**Comment by salanki** [comment]
@ruzickap: I'll happily donate $500 (paypal / crypto) if you can give this some attention. I'd rather support you than spending the time migrating away.
