### ISSUE TITLE
Default mounting of current working directory does not work

### ISSUE THREAD

**Issue by sparsick** [ruzickap/packer-templates#362]
Using vagrant box `peru/ubuntu-20.04-desktop-amd64` in version `20220202.01` does not mount my current working directory to '/vagrant' in the guest, as described as default behavior  in the [Vagrant docs](https://www.vagrantup.com/docs/synced-folders). 

**Expected result:**
Normally, I can see in the log following output:

```shell
==> ubuntu-vbox: Mounting shared folders...
    ubuntu-vbox: /vagrant => /home/sparsick/dev/workspace/vagrant-working-dir

```
**Environment information**
OS: Linux Mint 20.3 x86_64 
Kernel: 5.13.0-28-generic 
Shell: zsh 5.8 
Vagrant Version: 2.2.19
Virtualbox Version:  6.1.32 r149290 (Qt5.12.8)

**Known Workaround**
Add in your `Vagrantfile` following configuration:

```ruby
   config.vm.network "private_network", ip: "192.168.56.10"
   config.vm.synced_folder ".", "/vagrant"
```

⚠️ You have to install `nfs-common` and `nfs-kernel-server` on your host.

**Comment by ruzickap** [comment]
Thanks for reporting it I'll look at it.

The initial idea is to keep Ubuntu Desktop with "default" packages (without adding any packages):

https://github.com/ruzickap/packer-templates/blob/05da35e6a64330aa754eb087cfafcafe4d2088a6/http/ubuntu-desktop/preseed.cfg#L371

But this seems like a valid request...

**Comment by sparsick** [comment]
It seems that the `automount` of Vagrant uses `vboxfs`. Maybe it is enough to install the Virtualbox Guest Extension.

**Comment by ruzickap** [comment]
Hello.

I was looking at it and it should be possible to mount the directory from your computer to Vagrant VM, because VirtualBox Guest Extension are installed. 

This is what I used:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/1434387/155394229-3354b80a-0b6e-4374-9d90-d9a8f08b33bd.png">

Please try it and let me know...

**Comment by sparsick** [comment]
@ruzickap I try it out and it works. Now I'm wondering why vagrant automount doesn't work with your box.

**Comment by sparsick** [comment]
I compared the vagrant up output from your box to other boxes, where the automounting works. 

Output of your box:
```text
==> ubuntu-vbox: Machine booted and ready!
==> ubuntu-vbox: Checking for guest additions in VM...
==> ubuntu-vbox: Running provisioner: shell...
````

Output of a box with working automount:
```text
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 6.0.8
    default: VirtualBox Version: 6.1
==> default: Mounting shared folders...
    default: /vagrant => /home/sparsick/dev/workspace/vagrant-test
```

It seems that vagrant doesn't recognize the installed VirtualBox Guest Extension (it is not installed properly) of your box.

**Comment by ruzickap** [comment]
Thank you...
Can you give me some example of the "linux box" where it is running correctly ?
I'll check how it is installed there...

**Comment by sparsick** [comment]
Here the project https://github.com/mokote/vagrantboxes I checked with. I tried the debian9 and the ubuntu1604 one.
