### ISSUE TITLE
Are static IP assignments supported?

### ISSUE THREAD

**Issue by poige** [ruzickap/packer-templates#37]
Or just DHCP?

**Comment by ruzickap** [comment]
Not sure if I understand the question.
By default DHCP is enabled for the interface (like everywhere). If you want to change you can do it inside OS.

**Comment by poige** [comment]
Described in manual at [Networking](https://www.vagrantup.com/docs/networking/public_network.html)::Static IP.

**Comment by ruzickap** [comment]
I have never tried it - so I can not tell you if it's working or not.

Give it a try and come back if it is not working - then we can try to find some solution for it...

**Comment by poige** [comment]
> I have never tried it

I'd suppose it needs special (custom) handling added to the box and won't work "automagically".

**Comment by ruzickap** [comment]
In such case "static IP assignments" is not working.
(PRs are welcome)
