### ISSUE TITLE
Can't Configure Windows Defender Settings

### ISSUE THREAD

**Issue by mthbrown** [ruzickap/packer-templates#375]
Hi,

I'm currently using the latest `peru/windows-10-enterprise-x64-eval` box and although everything works fine, whenever I click on "Open Windows Security", it does nothing. Meanwhile, other options under `Backup`, etc work. It is only "Open Windows Security" that doesn't open so I can't do things such as whitelist certain directories, disable real-time protection, etc. Any ideas? Thanks

![windows_security](https://user-images.githubusercontent.com/22183215/161451803-349a76aa-ecca-44f8-b16f-25e7a5f0242f.jpeg)

**Comment by ruzickap** [comment]
I'm sorry, but this is more like Windows Operating System question...
I have no idea how to fix it or why it is not working... :-(
(I'm not a Windows user)

**Comment by mthbrown** [comment]
Thanks @ruzickap. I think it might have to do with the packaging of the image. Why? Because if I take any of [gusztavvargadr's](https://app.vagrantup.com/gusztavvargadr/boxes/windows-10) boxes and convert them from Virtualbox to libvirt using `vagrant mutate` they don't have this issue. I'd prefer to use your boxes as they are a native option and I'm trying to understand why this is happening. I'm not good at Packer but is there anything specific that he's doing that you're not (or vice versa)? Thanks

**Comment by mthbrown** [comment]
I tried the below versions and they all have the same issue so it looks like it has been around for some time:

```
peru/windows-10-enterprise-x64-eval        (libvirt, 20200901.01)
peru/windows-10-enterprise-x64-eval        (libvirt, 20220202.01)
peru/windows-10-enterprise-x64-eval        (libvirt, 20220402.01)
```
