### ISSUE TITLE
Add support for Ubuntu 22.10

### ISSUE THREAD

**Issue by steve-todorov** [ruzickap/packer-templates#380]
Hey,

I have been using your images for a while now - great work! :) 

Since I needed Ubuntu 22.10 (KVM) for some devops experiments I decided to clone your repo and try to add the template / configuration myself. Unfortunately it looks like you can no longer use the [Legacy Ubuntu Installer](http://archive.ubuntu.com/ubuntu/dists/jammy/main/installer-amd64/current/legacy-images/) approach: 

```
Legacy Ubuntu Server Installer Images
The Legacy Ubuntu Server Installer is no longer available.
```

From what I understand the new way of doing this is through PXELinux and TFTP as mentioned here:
https://discourse.ubuntu.com/t/netbooting-the-live-server-installer/14510

Have you had time to investigate this yet?

**Comment by ruzickap** [comment]
Not yet...
Using PXE / TFTP way may be easy for libvirt/qemu, but it will not be so easy for VirtualBox. 

That is the reason why I tried to use the legacy option (with booting ISO image) as "long" as possible - because that method works "everywhere" and is easy to setup.

**Comment by steve-todorov** [comment]
Thanks for the fast response! 

I understand. I haven't used VirtulBox for more than 10 years now as my work mainly involves libvirt/qemu. 
However, I found out these links while checking out for PXE support so I decided to post them here as they might help: 

* https://www.oreilly.com/library/view/android-system-programming/9781787125360/dacb2edf-3bd1-40c6-8084-06eb074ba976.xhtml
   > * Create a `$HOME/.VirtualBox/TFTP` folder. The built-in TFTP root is at `$HOME/.VirtualBox/TFTP` on Linux or `%USERPROFILE%\.VirtualBox\TFTP` on Windows.
   > * Usually, the default boot image name is `pxelinux.0` for PXE boot, but it is `vmname.pxe` for the VirtualBox built-in PXE. For example, if we use pxeAndroid as the virtual machine name, we have to make a copy of pxelinux.0 and name it pxeAndroid.pxe under the TFTP root folder.

* https://github.com/defunctzombie/virtualbox-pxe-boot

**Comment by steve-todorov** [comment]
Oops... Forgot to reply in time. This is still an issue so maybe re-open it? :)
