### ISSUE TITLE
Libvirt Version of the Win Server 22 is missing

### ISSUE THREAD

**Issue by jaunruh** [ruzickap/packer-templates#381]
Your Win 22 Server version for the `libvirt` provider seems to be missing [here](https://app.vagrantup.com/peru/boxes/windows-server-2022-standard-x64-eval). Is that intentional?

**Comment by CM2Walki** [comment]
Related to #370

**Comment by ruzickap** [comment]
Seem like there are "new" 2k22 VirtIO drivers: https://github.com/ruzickap/ansible-role-virtio-win/pull/31

Let me rebuild the Windows 2022 images...

**Comment by jaunruh** [comment]
Actually the `libvirt` version seems to be missing for all Win Server versions. 22, 19, 16 and 12r2 are all missing the `libvirt` provider. I tried to clone the repo and execute the `build.sh` file for Win 22 `libvirt` and I was getting the error `Adding the driver package failed : A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider` in the `ansible-role-virtio-win` role for `pvpanic`. Don't know if that is related.

**Comment by CM2Walki** [comment]
For people that also had pipelines break because they rely on a Windows `libvirt` box. The boxes: `jborean93/WindowsServer2012`, `jborean93/WindowsServer2012r2`, `jborean93/WindowsServer2016`, `jborean93/WindowsServer2019` provide temporary alternatives until this problem has been fixed.

**Comment by ruzickap** [comment]
Yes it is true. 
The error `Adding the driver package failed : A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider` is causing the problems for Win Server 22...

**Comment by ruzickap** [comment]
It should be fixed. 
Seems like one certificate which was used for signing the Redhat VirtIO drivers expired. 
I fixed it and rebuild all images...

Let me know if it is working for you...

**Comment by ruzickap** [comment]
Thanks...

Closing...
