### ISSUE TITLE
Bridge Network in Ubuntu20.04 box

### ISSUE THREAD

**Issue by nishtsh1** [ruzickap/packer-templates#384]
Tried ubuntu-20.04 box. Created Vagrantfile and tried to configure bridge networking in it
config.vm.define :kvm_gpu_passthrough do |kvm|
kvm.vm.box = "peru/my_ubuntu-20.04-server-amd64"
kvm.vm.network :public_network
end
end
Vagrant.configure("2") do |config|
# Public Network for VM
config.vm.define :kvm_gpu_passthrough do |kvm|
kvm.vm.network :public_network,
:dev => "eth0",
:mode => "bridge",
:type => "bridge"
end
end

I got error like Can't attach eth0 to vnet0: Operation not permitted.
My questions is: ****How can I enable bridge network in KVM and use it in Vagrantfile?**
The default network in VM is NAT which is again not working. I need to enable bridge network in VM using Vagrantfile

**Comment by ruzickap** [comment]
Hello.

This seems like a Vagrant problem. 
I have never tried it myself, but please check it out with Vagrant team or try different box...

Thank you

**Comment by nishtsh1** [comment]
HI,

Tried on different box and it's working.

Thank You
