### ISSUE TITLE
Windows 10 builds fail during Ansible provisioning due to missing Packer connection plugin

### ISSUE THREAD

**Issue by nrvale0** [ruzickap/packer-templates#4]
```pre
2017/12/31 12:48:39 ui:     windows-10-enterprise-x64-eval: fatal: [default]: FAILED! => {"msg": "the connection plugin 'packer' was not found"}
    windows-10-enterprise-x64-eval: fatal: [default]: FAILED! => {"msg": "the connection plugin 'packer' was not found"}
    windows-10-enterprise-x64-eval:     to retry, use: --limit @/home/\<redacted\>/workspace/github/ruzickap/packer-templates/ansible/win.retry
2017/12/31 12:48:39 ui:     windows-10-enterprise-x64-eval:     to retry, use: --limit @/home/nrvale0/workspace/github/ruzickap/packer-templates/ansible/win.retry
```

I'm not familiar enough with Ansible to know what might be the problem here. Any ideas? More than willing to submit a PR if I can figure it out.

**Comment by ruzickap** [comment]
Hello.

It looks like you are missing the "winrm packer communicator" for ansible located in `connection_plugins` directory:

https://www.packer.io/docs/provisioners/ansible.html

Maybe you can try to fix it by running:

```
# Install WinRM communicator for Packer (https://www.packer.io/docs/provisioners/ansible.html#winrm-communicator)
mkdir -p ~/.ansible/plugins/connection_plugins
wget -P ~/.ansible/plugins/connection_plugins/ https://raw.githubusercontent.com/hashicorp/packer/master/test/fixtures/provisioner-ansible/connection_plugins/packer.py
sed -i.orig 's@#connection_plugins =.*@connection_plugins = ~/.ansible/plugins/connection_plugins/@' /etc/ansible/ansible.cfg
```

or just follow the steps from the official Packer manual from the url above.

**Comment by ruzickap** [comment]
If you are still in trouble please check this gist to see how the Packer with WinRM communicator / Ansible / Qemu and enable Packer's Winrm communicator should be installed in Fedora

https://gist.github.com/ruzickap/e1b6ac258425b6d314f0c3cab07a5570#file-packer_ansible_qemu_fedora-sh

**Comment by nrvale0** [comment]
Petr,

Thanks for the response. Indeed this did fix the issue.

It seems that I was actually on the right track when I previously found mention in the Packer docs. I assumed the Ansible toolchain (again, not something I've spent much time using) probably wanted it to be installed via pip or some other Ansible CLI tool similar to Chef/knife or Puppet/puppet module and that I had missed a step in setup. Might be time to get an Ansible book. :)

Thx again and Happy New Year!
