### ISSUE TITLE
Ubuntu 22.04 jammy?

### ISSUE THREAD

**Issue by derobert** [ruzickap/packer-templates#406]
Any plans for an https://app.vagrantup.com/peru/boxes/ubuntu-22.04-server-amd64 Ubuntu 22.04 LTS image?

**Comment by ruzickap** [comment]
That would be a problem...

I'm using the `mini.iso` (http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/) image to boot and install various Ubuntu versions.

Canonical deprecated the CD-ROM installations using `mini.iso` in Ubuntu 22.04 http://archive.ubuntu.com/ubuntu/dists/jammy/main/installer-amd64/current/legacy-images/.

**Comment by steve-todorov** [comment]
It's probably worth mentioning #380  which I opened a while back  but the @stale bot closed it. 

It is possible to use `tftp` for this (mentioned in #380), but I never had the time to check that out and follow it through. :/

**Comment by steve-todorov** [comment]
ping. :)

**Comment by abbbi** [comment]
@steve-todorov 
FYI, the roboxes project provides images for all HV's available:

https://app.vagrantup.com/generic/boxes/ubuntu2204
