### ISSUE TITLE
WindowsServer libvirt images slow

### ISSUE THREAD

**Issue by achelos-fde** [ruzickap/packer-templates#423]
I am using the WindowsServer-libvirt images (tried 2016, 2019 and 2022) for setting up a VM using Vagrant.
In the VM I am compiling a quite big C project.
The compilation on the VM takes about 3.5 hours.

If I set up a Virtualbox-VM using the corresponding Virtualbox image the compilation takes only less than 1.5 hours on identical hardware.

So, if I don't miss anything the only difference between the images is the virtualization (Virtualbox <-> libvirt).

Can anybody advise me how to speed up the libvirt VM ?

**Comment by ruzickap** [comment]
It is hard to say...
I tried to build the automation which creates the images with "best practices" related to VM performance. 

I'm using VirtIO everywhere it is possible, [Qemu Guest Agent](http://wiki.libvirt.org/page/Qemu_guest_agent) and maybe few more.

Anyway the automation was developed several years ago and what was great at that time may not be actual in these days...

If somebody can suggest better approach I can look at it and implement it...

The comments above are related to the box image itself.

You also need to properly configure your libvirt/qemu to use as much as possible from your hardware. I'm pretty sure there are many guides how to do it...
