### ISSUE TITLE
libvirt Windows images missing?

### ISSUE THREAD

**Issue by achelos-fde** [ruzickap/packer-templates#442]
On https://app.vagrantup.com/peru/boxes/windows-server-2016-standard-x64-eval I can't find the libvirt images anymore.
Is this a mistake or won't there be any libvirt builds anymore?

**Comment by ruzickap** [comment]
It is a mistake. 
I'm aware of it and I'm going to rebuild the `libvirt` image asap...

Thank you for reporting it...

**Comment by ruzickap** [comment]
It should be fixed now...
Let me know if it is working for you...

**Comment by achelos-fde** [comment]
The image is working fine.
Thanks for the quick action - very appreciated.
