### ISSUE TITLE
windows-10-enterprise-x64-eval failed with multiple CPUs

### ISSUE THREAD

**Issue by knowonething** [ruzickap/packer-templates#490]
Does this box support multiple CPUs?

[peru](https://app.vagrantup.com/peru)/[windows-10-enterprise-x64-eval](https://app.vagrantup.com/peru/boxes/windows-10-enterprise-x64-eval)

**Comment by ruzickap** [comment]
I guess so...
It was build using 4 CPUs: https://github.com/ruzickap/packer-templates/blob/201a2588eeb0c562e3d641e9b645e18e76c14e44/windows.json#L172

**Comment by knowonething** [comment]
OK, I'll try again. thanks.
