### ISSUE TITLE
Windows boxes need to be sysprep'ed

### ISSUE THREAD

**Issue by pbrezina** [ruzickap/packer-templates#5]
Hi, thank you for your work around windows boxes for vagrant. We appreciate it.

I choose your boxes to prepare Active Directory machines as part of our sssd test suite [1]. We need to setup more then one Active Directory domain in a forest which is currently problematic. Images in your boxes were not prepared with `sysprep` (as I see in the other issue [2]), therefore they all have the same `SID` and we have to use different images if we want to create more domains, which is inconvenient.

Now, I tried to do it myself before creating this ticket but I end up with the same error message as you got in [2]. I don't have time to focus on this now but I will try to solve it every now and then. But if you can spent some time on it and prepare new boxes, please do.

Thank you.

[1] https://github.com/pbrezina/sssd-test-suite
[2] https://github.com/ruzickap/packer-templates/issues/3

**Comment by ruzickap** [comment]
Hello.

I do have a plan to rebuild the images and use sysprep. Actually I'm waiting for Microsoft to release downloadable Windows iso where I can install ssh daemon (and get rid of WinRM)
If I replace WinRM by SSH then many things will be easier. (but it has nothing to do with sysprep).

I hope I'll look at #3 soon.

**Comment by ruzickap** [comment]
Hello. I rebuilt the images with sysprep - so please test it.
I'm going to close this issue so we can continue in #3 .

**Comment by pbrezina** [comment]
Works great. Thank you.
