### ISSUE TITLE
Bug: peru/windows-10-enterprise-x64-eval no longer has virtualbox provider on Vagrant Cloud

### ISSUE THREAD

**Issue by gblewis1** [ruzickap/packer-templates#518]
**Describe the bug**
When bringing the peru/windows-10-enterprise-x64-eval box up with provider: virtualbox, I get this error

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'peru/windows-10-enterprise-x64-eval' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 20240201.01
==> default: Loading metadata for box 'peru/windows-10-enterprise-x64-eval'
    default: URL: https://vagrantcloud.com/api/v2/vagrant/peru/windows-10-enterprise-x64-eval
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: peru/windows-10-enterprise-x64-eval
Address: https://vagrantcloud.com/api/v2/vagrant/peru/windows-10-enterprise-x64-eval
Requested provider: virtualbox (amd64)
```

**To Reproduce**
Follow instructions at https://app.vagrantup.com/peru/boxes/windows-10-enterprise-x64-eval and attempt to bring up using VirtualBox provider.

Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.box_version = "20240201.01"
end
```

Command:
```
VAGRANT_DEFAULT_PROVIDER=virtualbox vagrant up
```

**Expected behaviour**
Box should come up.

**Additional context**
Note that https://app.vagrantup.com/peru/boxes/windows-10-enterprise-x64-eval no longer lists virtualbox as a provider near the bottom of the page, even though the documentation for the box still mentions it can be used with virtualbox.

**Comment by ruzickap** [comment]
I haven't used the "new" packer versions yet, but I guess you will need the `virtualbox` provider: https://developer.hashicorp.com/packer/integrations/hashicorp/virtualbox

**Comment by ruzickap** [comment]
Thank you Gavin for your suggestion and please please accept my apologies for slow response.

I do not plan to do any other changes to the repository, because it will require testing / fixing old bugs / updating components / etc...

I updated the `README.md` with the outdated message: https://github.com/ruzickap/packer-templates/pull/524

Thank you for understanding...
