### ISSUE TITLE
Box not working with VirtualBox 6.1+

### ISSUE THREAD

**Issue by KerbenII** [ruzickap/packer-templates#54]
This parameter name:
https://github.com/ruzickap/packer-templates/blob/e0da018711a9767636ffb4a4d20a12f2428847ba/Vagrantfile-linux.template#L21

does not exist in VirtualBox 6.1 and up.

There are two possible solutions:
1. Remove that line from default customization commands (and allow enduser decide if he should implement this)
2. Use one of the workaround (for example this: https://github.com/hashicorp/vagrant/issues/4649#issuecomment-349933328 ) in order to determine VirtualBox version, and based on it determine if we should execute:

`    virtualbox.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
`
or
`    virtualbox.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
`

**Comment by ruzickap** [comment]
Thanks a lot for finding it.

I removed the parameter from `Vagrantfile` templates, because I'm going to use/build images only for VirtualBox 6.1 and later versions...

See you...
