### ISSUE TITLE
The box you're attempting to add doesn't support the provider

### ISSUE THREAD

**Issue by juicyarts** [ruzickap/packer-templates#58]
```
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: peru/windows-server-2012_r2-standard-x64-eval
Address: https://vagrantcloud.com/peru/windows-server-2012_r2-standard-x64-eval
Requested provider: [:virtualbox]
```

As far as i can see in the readme the virtualbox provider should work . Am i missing something here?

**Comment by maccopper2** [comment]
@ruzickap did update a number of boxes in vagrant 2020-02-04 (yesterday).

As you can see here
https://app.vagrantup.com/boxes/search?page=1&provider=&q=peru&sort=downloads&utf8=%E2%9C%93
many of the boxes are currently only published for the Provider libvirt, not for Provider VirtualBox.

As the old boxes are not visible anymore, you can not use the box for VirtualBox currently.

I do have the same Problem with box peru/ubuntu-18.04-server-amd64, see #59

**Comment by ruzickap** [comment]
I know ... I'm sorry for that.
I have some issue with building the images. 
I hope I'll fix it asap...

**Comment by ruzickap** [comment]
All images were rebuild and should be accessible (working).

Please let me know if you still have issues...

**Comment by juicyarts** [comment]
Currently downloading and it works! Thanks a lot for your efforts!
