### ISSUE TITLE
peru/ubuntu-18.04-server-amd64 20200204.01 virtualbox missing

### ISSUE THREAD

**Issue by maccopper2** [ruzickap/packer-templates#59]
The Vagrant image "peru/ubuntu-18.04-server-amd64" in version 20200204.01 is only published for libvirt, not for virtualbox.

See:
https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=peru+ubuntu+server

**Comment by ruzickap** [comment]
All images were rebuild and should be accessible (working).

Please let me know if you still have issues...

**Comment by maccopper2** [comment]
Thank you for the fast reaction.

My colleagues do use the peru/ubuntu-19.04-desktop-amd64. It would be very kind, to add this, too.

**Comment by ruzickap** [comment]
Actually with Ubuntu Desktop it's more complicated. The Ubuntu 19.04 is no longer "supported" on the release page http://releases.ubuntu.com/. 

I tried to to build the Ubuntu 19.10 Desktop, but I got some issues with networking: https://github.com/hashicorp/vagrant/issues/11378

I'm sorry, but currently I do not have the Ubuntu Desktop 19.xx box image.

I can build the Ubuntu Desktop LTS 18.04 version if you want, but it's quite old...

**Comment by aparedero** [comment]
@ruzickap It would be great if Ubuntu LTS 18.04 would be accessible again (Please accept my apologizes about sending an email some hours ago, I should write you about the suddenly missing box here)

**Comment by ruzickap** [comment]
I'm sorry - I didn't know that somebody is using the Ubuntu Desktop 18.04. 

Next time I'm going to be more careful before deleting the old boxes.

Anyway - it's back again: https://app.vagrantup.com/peru/boxes/ubuntu-18.04-desktop-amd64

Let me know if it is working fine...

I will focus on the Ubuntu Desktop 19.10, but this will take some more time...

**Comment by maccopper2** [comment]
As Ubuntu 19.04 is no longer supported, I convinced my colleagues to standardize our environment with using peru/ubuntu-18.04-desktop-amd64. (LTS)

I will test https://app.vagrantup.com/peru/boxes/ubuntu-18.04-desktop-amd64 as soon as I arrive at work.

I thank you very much for your fast response. I hope I did not waste too much time asking for desktop 19.04.

**Comment by ruzickap** [comment]
It's always best practice to use LTS versions if you plan to use it for longer time or as "base" for future work.

I'm glad to help you...
