### ISSUE TITLE
Windows 2012R2 reboot loop

### ISSUE THREAD

**Issue by cfowler-github** [ruzickap/packer-templates#6]
Your latest packaging of Windows 2012R2 (20180401.01) cannot be used for building a Domain Controller as it's stuck in a permanent need to reboot any time you attempt to install AD-Domain-Services. Digging around online it sounds like the Windows Internal Database can be corrupted during install some times, and your image might just require a rebuild.   

```
Install-WindowsFeature -Name AD-Domain-Services,DNS -IncludeManagementTools

    dc: Install-WindowsFeature : The request to add or remove features on the
    dc: specified server failed.
    dc: The operation cannot be completed, because the server that you specified
    dc: requires a restart.
    dc: At C:\tmp\vagrant-shell.ps1:3 char:1
    dc: + Install-WindowsFeature -Name AD-Domain-Services,DNS -IncludeManagementTools
    dc: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    dc:     + CategoryInfo          : DeviceError: (@{Vhd=; Credent...Name=localhost}:
    dc:    PSObject) [Install-WindowsFeature], Exception
    dc:     + FullyQualifiedErrorId : DISMAPI_Error__Failed_Reboot_Required,Microsoft.
    dc:    Windows.ServerManager.Commands.AddWindowsFeatureCommand
```

No amount of rebooting will satisfy the requirement. I've rolled back to the previous version of your image for now.

**Comment by ruzickap** [comment]
Thanks for reporting that...

Do you have any idea how this kind of corruption can be detected?

I'll rebuild the image and let you know, but it will be handy if I can detect it somehow...

**Comment by cfowler-github** [comment]
Unfortunately no. I looked for a way to dig through the registry and see the problem, couldn't find one. Tried running the command just using -WhatIf as in:

`Install-WindowsFeature -Name AD-Domain-Services,DNS -IncludeManagementTools -WhatIf`

No dice there either. Windows just isn't very amenable to automation and the error detection needed to make it work well, unfortunately. If I ever come across a solution I'll let you know.

**Comment by ruzickap** [comment]
:-)

Ok... I recreated the Windows 2012 Server images for libvirt/virtualbox - can you check it please?

Thank you...

**Comment by cfowler-github** [comment]
Yep, it's working now. Thanks!

**Comment by ruzickap** [comment]
Thank you...
