### ISSUE TITLE
fails to find checksum for ubuntu libvirt build

### ISSUE THREAD

**Issue by hemna** [ruzickap/packer-templates#60]
waboring@hpvirt1:~/devel/test/packer-templates:(git::master) $  ./build.sh ubuntu-18.04-server-amd64-libvirt

*** ubuntu | ubuntu-18.04-server-amd64 | ubuntu-18.04-server-amd64-libvirt - libvirt/qemu
* NAME: ubuntu-18.04-server-amd64, UBUNTU_TYPE: server, UBUNTU_CODENAME: bionic, PACKER_FILE: ubuntu-server.json
+ '[' '!' -f /var/tmp/packer-templates-images/ubuntu-18.04-server-amd64-libvirt.box ']'
+ '[' false = true ']'
+ packerio build -only=qemu -color=false -var headless=true ubuntu-server.json
+ tee /var/tmp/packer-templates-images/ubuntu-18.04-server-amd64-libvirt-packer.log
1 error(s) occurred:

* Couldn't extract checksum from checksum file: no checksum found in: http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/SHA256SUMS

**Comment by ruzickap** [comment]
Hello.

I know about this issue - it's a bug in Packer. You need to downgrade your packer installation to version `1.5.1`.

See more details here: https://github.com/hashicorp/packer/issues/8774

Take care...

**Comment by ruzickap** [comment]
Note: This should be fully fixed in Packer 1.5.5
