### ISSUE TITLE
Fedora libvirt plugin issue

### ISSUE THREAD

**Issue by rajganeshp** [ruzickap/packer-templates#8]
[root@localhost raj]# vagrant plugin install vagrant-libvirt
==> vagrant: A new version of Vagrant is available: 2.1.2!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching: formatador-0.2.5.gem (100%)
Fetching: excon-0.62.0.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: mini_portile2-2.3.0.gem (100%)
Fetching: nokogiri-1.8.4.gem (100%)
Building native extensions.  This could take a while...
Fetching: ruby-libvirt-0.7.1.gem (100%)
Building native extensions.  This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /root/.vagrant.d/gems/2.4.3/gems/ruby-libvirt-0.7.1/ext/libvirt
/opt/vagrant/embedded/bin/ruby -r ./siteconf20180808-3963-njo12e.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /root/.vagrant.d/gems/2.4.3/extensions/x86_64-linux/2.4.0/ruby-libvirt-0.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/2.4.3/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /root/.vagrant.d/gems/2.4.3/extensions/x86_64-linux/2.4.0/ruby-libvirt-0.7.1/gem_make.out

[root@localhost raj]#

**Comment by ruzickap** [comment]
Hello Raj.

Did you installed these libraries before you started the installation `vagrant plugin install vagrant-libvirt` ?

```
libvirt-client
libvirt-daemon-kvm
libvirt-devel
```

**Comment by rajganeshp** [comment]
Yes, I did. if you have time, can you try with fresh install of Fedora? Thanks.

**Comment by ruzickap** [comment]
Hello. I'm using this ansible playbook to install the environment for building/testing Packer templates in Fedora 28:

https://github.com/ruzickap/packer-templates/blob/master/ansible/build_remote_ssh_fedora.yml

All the necessary packages are mentioned here: https://github.com/ruzickap/packer-templates/blob/master/ansible/build_remote_ssh_fedora.yml#L8-L27
(you also need to install rpmfusion repository)

**Comment by rajganeshp** [comment]
Thanks Petr. I've never used Ansible. Do you have any blog posts or article
which will show to get this setup. Just want to run few Vagrant VMs on my
Fedora.

Thanks,
Raj

**Comment by ruzickap** [comment]
Ok... 

Try these commands:

```
dnf remove vagrant

dnf install -y https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.rpm

dnf install -y gcc libvirt-daemon-kvm qemu-kvm libvirt-devel rdesktop
CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt --with-libvirt-lib=/usr/lib64/libvirt" vagrant plugin install vagrant-libvirt

mkdir my_windows-10-enterprise-x64-eval
cd my_windows-10-enterprise-x64-eval
vagrant init peru/my_windows-10-enterprise-x64-eval
VAGRANT_DEFAULT_PROVIDER=libvirt vagrant up
```

It should be working...

**Comment by rajganeshp** [comment]
Thanks. was able to pass that hurdle, but ran into another issue. not sure
why it's using Virtualbox

[raj@localhost my_windows-10-enterprise-x64-eval]$ sudo
VAGRANT_DEFAULT_PROVIDER=libvirt vagrant up --provider libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'peru/my_windows-10-enterprise-x64-eval' is up
to date...
==> default: Creating image (snapshot of base box volume).
Volume for domain is already created. Please run 'vagrant destroy' first.
[raj@localhost my_windows-10-enterprise-x64-eval]$ vagrant box list
There are no installed boxes! Use `vagrant box add` to add some.
[raj@localhost my_windows-10-enterprise-x64-eval]$ sudo vagrant box list
peru/my_windows-10-enterprise-x64-eval (libvirt, 20180801.01)
[raj@localhost my_windows-10-enterprise-x64-eval]$
[raj@localhost my_windows-10-enterprise-x64-eval]$
[raj@localhost my_windows-10-enterprise-x64-eval]$ vagrant destroy -f
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
[raj@localhost my_windows-10-enterprise-x64-eval]$ sudo vagrant destroy -f
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
[raj@localhost my_windows-10-enterprise-x64-eval]$

**Comment by ruzickap** [comment]
It looks like you have already defined libvirt volume there.

Check the "Storage Pool" and "Storage Volume" using `virsh` command.

You can maybe use `virt-manager` to see the details but examining the issue using `virsh` is probably better.

This should not happen if you have completely fresh Fedora installed. You probably did some testing before which created the volume.
