### ISSUE TITLE
Remote libvirt server and winrm

### ISSUE THREAD

**Issue by akarasulu** [ruzickap/packer-templates#83]
Thanks for the box it runs perfectly when running on a local libvirt machine. I'm trying to launch it from a client machine to fire up the box on a remote libvirt server but it seems to get stuck trying to winrm. Have you gotten such a configuration working before?

Here's my Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.guest = :windows

  config.vm.network :forwarded_port, guest: 5986, host: 5986, id: "winrm-ssl", auto_correct:true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct:true

  config.vm.boot_timeout      = 1000
  config.vm.communicator      = "winrm"
  config.vm.guest             = :windows
  config.windows.halt_timeout = 15
  config.winrm.password       = "vagrant"
  config.winrm.retry_limit    = 30
  config.winrm.username       = "vagrant"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.host = "vms0"
    libvirt.memory = 1024
    libvirt.cpus = 2
    libvirt.nested = true
    libvirt.uri = "qemu+ssh://root@vms0/system"
  end
end
```

I keep getting winrm trying to connect to the private management network IP:

```
DEBUG winrmshell: initializing WinRMShell
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 192.168.121.198
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: negotiate
DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.198:5985/wsman
... several more
```

Trying to figure out how to get winrm to use the forwarded port. Any ideas?

**Comment by ruzickap** [comment]
Hi.

I have never tried such configuration which you described. I'm not sure if this is supported by Vagrant + vagrant-libvirt. 

Maybe try to ask people from vagrant-libvirt project if they are supporting it.

I'm testing+running these boxes only on the local machine...

**Comment by akarasulu** [comment]
Thanks for the response. Remote libvirt works perfectly for Linux and SSH but the problem is just winrm. I'll inquire with the vagrant-libvirt folks. Regards.

**Comment by akarasulu** [comment]
Just for others, I tried setting the winrm host to localhost with the port forwards above in my Vagrantfile and that did not work either.
