### ISSUE TITLE
Server 2019: Enable OpenSSH Server

### ISSUE THREAD

**Issue by abbbi** [ruzickap/packer-templates#9]
hi,

Windows 2019 seems to have OpenSSH server included. It can be installed vai Windows Capability, for example:

Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

Maybe it would make sense to include it in the image so one could use ssh to access the system instead of the slow WinRM connection during VM config phase?

**Comment by ruzickap** [comment]
That's correct.

These kind of customizations are for applied here: https://app.vagrantup.com/peru/boxes/my_windows-10-enterprise-x64-eval, where I'm installing handy OpenSSH and other "handy" tools...

There is no such customization in default images...
Anyway the WinRM is still official way how to "access" windows remotely compared to OpenSSH.

**Comment by mihai-satmarean** [comment]
the topic is closed, but still there is no good pointer on where and how is incorporated in the answer file. Would you be able to help there?
Thanks!

**Comment by ruzickap** [comment]
Unfortunately no :-( I'm not advanced windows user... You will probably need to look to some Microsoft forums.

I have no idea how to enable OpenSSH server inside answer file. 
(If you find it out please put some comment / URL here)

Thank you
