### ISSUE TITLE
VBoxGuestAdditions.iso left in home folder for Ubuntu 20.04 Desktop

### ISSUE THREAD

**Issue by felipecassiors** [ruzickap/packer-templates#92]
I just started a new VM and the ISO was there.
![image](https://user-images.githubusercontent.com/29582865/82609476-fb305280-9b92-11ea-8da8-308c831faff3.png)

**Comment by ruzickap** [comment]
Thanks for reporting it...
Good catch.
I'll fix it asap...

**Comment by ruzickap** [comment]
I fixed the code generating the images.
I'll re-generate new images soon.

I'm going to keep this issue opened until new images will be uploaded to VagrantCloud and you will be able to test them...

**Comment by felipecassiors** [comment]
Awesome, I'm going to test it.

**Comment by felipecassiors** [comment]
@ruzickap, there is no `virtualbox` provider for the latest box: https://app.vagrantup.com/peru/boxes/ubuntu-20.04-desktop-amd64/versions/20200522.01

**Comment by ruzickap** [comment]
Yes I know... It needs 1 day to rebuild all images...
Please be patient... and give it a try tomorrow...

**Comment by ruzickap** [comment]
Can you please check it now? 

All images were updated...

Thank you

**Comment by felipecassiors** [comment]
Confirmed, the ISO is gone! :-D 

Thank you very much!
